### ISSUE TITLE
Match versioning with neo-cli

### ISSUE THREAD

**Issue by ksemaev** [neo-project/neo-modules#122]
Guys, can you please release plugins with the same version as neo-cli? Currently we have 2.10.3 here https://github.com/neo-project/neo-cli/releases and for plugins latest is 2.10.2 https://github.com/neo-project/neo-plugins/releases

So not only I'm not sure if plugins work with the latest version, also my CI/CD pipe fails, as I use the same VERSION var to download both the cli and plugins

**Comment by cloud8little** [comment]
https://github.com/neo-project/neo-modules/releases/tag/v2.10.3 was released.
