### ISSUE TITLE
Send rpc return different json response from neo-cli  when multisig is incompeleted

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-modules#138]
Issue: In NEO3, when in multisigaddress, someone use ```sendfrom``` rpc to transfer asset from it, rpc response returns different format from neo-cli(I mean if he transfers the same asset from the same multisigaddress using command line in neo-cli). Seems the format from RPC is an old format which is the same as NEO2.X. It's not able to be ```sign``` in neo-cli.
![image](https://user-images.githubusercontent.com/38493437/65738813-b47a7d80-e115-11e9-9945-53610c64b06c.png)
Step to Reproduce: 
1. Create a multisigadress
2. Send some asset into it.
3. Using ```sendfrom``` rpc to transfer asset from this address.
4. Get the json response which is waiting for signing.
5. Using ```sign``` command line in neo-cli to sign it.
6. Fail.
Advice to Fix:
Make the rpc response the same as neo-cli content.

**Comment by cloud8little** [comment]
Although the use cases is not that common among the developers/neo-cli users, it is important to align with neo client behavior with RPC behavior, in this case is sendfrom/sendtoaddress request.

**Comment by shargon** [comment]
What plugin is involved?

**Comment by cloud8little** [comment]
rpcwalket

**Comment by shargon** [comment]
With command line should be shown

``Console.WriteLine($"Signed Output:\r\n{context}");``

https://github.com/neo-project/neo-cli/blob/7a7d961fbfa04a039c871311e1b35d82827c2451/neo-cli/Shell/MainService.cs#L337

and in your screen looks different

**Comment by cloud8little** [comment]
Here compares sendfrom with RPC request with send directly via command line:
Steps:
1. open wallet muti.json
2. sendfrom request with response return <response>.
3. use command line to open wallet wallet_5.json
4. sign <response> above
5. return error, expect to return Signed Output.
`2019-10-09 14:41:40: [ LOG ]  [-------------------------------]
2019-10-09 14:41:40: [ LOG ]  [ CONNECT  ] RPC.sendfrom
2019-10-09 14:41:40: [ LOG ]  [ REQUEST  ]{
2019-10-09 14:41:40:     "NODE_INDEX": 1,
2019-10-09 14:41:40:     "REQUEST": {
2019-10-09 14:41:40:         "id": 1,
2019-10-09 14:41:40:         "jsonrpc": "2.0",
2019-10-09 14:41:40:         "method": "sendfrom",
2019-10-09 14:41:40:         "params": [
2019-10-09 14:41:40:             "0x43cf98eddbe047e198a3e5d57006311442a0ca15",
2019-10-09 14:41:40:             "ATBr4mAH9Sq8D6v2wG79f9EmedhKjGw2x6",
2019-10-09 14:41:40:             "AJmNUqhr8Z3w9t9ogM6pWU4hxq127nMPuj",
2019-10-09 14:41:40:             5.00000000,
2019-10-09 14:41:40:             0.00000000,
2019-10-09 14:41:40:             "ATBr4mAH9Sq8D6v2wG79f9EmedhKjGw2x6"
2019-10-09 14:41:40:         ]
2019-10-09 14:41:40:     },
2019-10-09 14:41:40:     "RESPONSE": null,
2019-10-09 14:41:40:     "TYPE": "RPC"
2019-10-09 14:41:40: }
2019-10-09 14:41:40: [ LOG ]  run on service(1):  47.254.93.207:50022
2019-10-09 14:41:42: [ LOG ]  [ RESPONSE ]{
2019-10-09 14:41:42:     "jsonrpc": "2.0",
2019-10-09 14:41:42:     "id": 1,
2019-10-09 14:41:42:     "result": {
2019-10-09 14:41:42:         "type": "Neo.Network.P2P.Payloads.Transaction",
2019-10-09 14:41:42:         "hex": "0005ae3b497d320be117004bb473cd7db0d1dc7550f20e144700e1f505000000000cfd230000000000ea14200000017d320be117004bb473cd7db0d1dc7550f20e14470151551420d007c675446161dbc0c833f83410d3accb3eeb147d320be117004bb473cd7db0d1dc7550f20e144753c1087472616e736665721415caa04214310670d5e5a398e147e0dbed98cf4368627d5b52f1",
2019-10-09 14:41:42:         "items": {
2019-10-09 14:41:42:             "0x47140ef25075dcd1b07dcd73b44b0017e10b327d": {
2019-10-09 14:41:42:                 "script": "522102166b93d66306d106a85caa02c4d36b72f85e7db69e324f4989ecea696d87f5e421036f9a8087d0dc64b5161a15dd02faad1a729c5ba7048f3bc60cee0138aa3e1f015268c7c34cba",
2019-10-09 14:41:42:                 "parameters": [
2019-10-09 14:41:42:                     {
2019-10-09 14:41:42:                         "type": "Signature"
2019-10-09 14:41:42:                     },
2019-10-09 14:41:42:                     {
2019-10-09 14:41:42:                         "type": "Signature"
2019-10-09 14:41:42:                     }
2019-10-09 14:41:42:                 ],
2019-10-09 14:41:42:                 "signatures": {
2019-10-09 14:41:42:                     "036f9a8087d0dc64b5161a15dd02faad1a729c5ba7048f3bc60cee0138aa3e1f01": "33bb6a9044fb8e9a8f5e6feca8c2e7614ade1ee03ac88321ba0faa8ada31341ff95bfc710b58f03dfcfe9a92c2629e729fecd70a1820a79bbed56851eb95a5a5"
2019-10-09 14:41:42:                 }
2019-10-09 14:41:42:             }
2019-10-09 14:41:42:         }
2019-10-09 14:41:42:     }
2019-10-09 14:41:42: }`

`2019-10-09 14:42:14: [ LOG ]  test_normal_126_jsonObjectToSign--sign {'type':'Neo.Network.P2P.Payloads.Transaction','hex':'0005ae3b497d320be117004bb473cd7db0d1dc7550f20e144700e1f505000000000cfd230000000000ea14200000017d320be117004bb473cd7db0d1dc7550f20e14470151551420d007c675446161dbc0c833f83410d3accb3eeb147d320be117004bb473cd7db0d1dc7550f20e144753c1087472616e736665721415caa04214310670d5e5a398e147e0dbed98cf4368627d5b52f1','items':{'0x47140ef25075dcd1b07dcd73b44b0017e10b327d':{'script':'522102166b93d66306d106a85caa02c4d36b72f85e7db69e324f4989ecea696d87f5e421036f9a8087d0dc64b5161a15dd02faad1a729c5ba7048f3bc60cee0138aa3e1f015268c7c34cba','parameters':[{'type':'Signature'},{'type':'Signature'}],'signatures':{'036f9a8087d0dc64b5161a15dd02faad1a729c5ba7048f3bc60cee0138aa3e1f01':'33bb6a9044fb8e9a8f5e6feca8c2e7614ade1ee03ac88321ba0faa8ada31341ff95bfc710b58f03dfcfe9a92c2629e729fecd70a1820a79bbed56851eb95a5a5'}}}}
2019-10-09 14:42:14:
2019-10-09 14:42:14: [ LOG ]  test_normal_126_jsonObjectToSign--One or more errors occurred:
2019-10-09 14:42:14:
2019-10-09 14:42:14: [ LOG ]  test_normal_126_jsonObjectToSign--One of the identified items was in an invalid format.`

--------------------
Command line:
Steps:
1. open wallet muti.json
2. send using command line directly return <response>.
3. use command line to open wallet wallet_5.json
4. sign <response> above
5. return Signed Output.

```
neo> open wallet /root/NEO3-auto/NEO-TEST/src/resource/wallet/muti.json
password: ********
neo> send neo AJmNUqhr8Z3w9t9ogM6pWU4hxq127nMPuj 5                                                                                                                                                  password: ********                                                                                                                                                                                  SignatureContext:                                                                                                                                                                                   {"type":"Neo.Network.P2P.Payloads.Transaction","hex":"0071c5de327d320be117004bb473cd7db0d1dc7550f20e144700e1f505000000000cfd2300000000009515200000017d320be117004bb473cd7db0d1dc7550f20e14470151551420d007c675446161dbc0c833f83410d3accb3eeb147d320be117004bb473cd7db0d1dc7550f20e144753c1087472616e736665721415caa04214310670d5e5a398e147e0dbed98cf4368627d5b52f1","items":{"0x47140ef25075dcd1b07dcd73b44b0017e10b327d":{"script":"522102166b93d66306d106a85caa02c4d36b72f85e7db69e324f4989ecea696d87f5e421036f9a8087d0dc64b5161a15dd02faad1a729c5ba7048f3bc60cee0138aa3e1f015268c7c34cba","parameters":[{"type":"Signature"},{"type":"Signature"}],"signatures":{"036f9a8087d0dc64b5161a15dd02faad1a729c5ba7048f3bc60cee0138aa3e1f01":"4b042ffe52d6a3382de97fcb6c7ddf6b8f2ea81f2f91bd8163f506b25ad91f9216155f31e382ec97d6be7ef887d77b05844fd45098ac145a623bbc93d9245e58"}}}}                                                                                                                                     neo> open wallet /root/NEO3-auto/NEO-TEST/src/resource/wallet/wallet_5.json                                                                                                                         password: ********
neo> sign {"type":"Neo.Network.P2P.Payloads.Transaction","hex":"0071c5de327d320be117004bb473cd7db0d1dc7550f20e144700e1f505000000000cfd2300000000009515200000017d320be117004bb473cd7db0d1dc7550f20e14470151551420d007c675446161dbc0c833f83410d3accb3eeb147d320be117004bb473cd7db0d1dc7550f20e144753c1087472616e736665721415caa04214310670d5e5a398e147e0dbed98cf4368627d5b52f1","items":{"0x47140ef25075dcd1b07dcd73b44b0017e10b327d":{"script":"522102166b93d66306d106a85caa02c4d36b72f85e7db69e324f4989ecea696d87f5e421036f9a8087d0dc64b5161a15dd02faad1a729c5ba7048f3bc60cee0138aa3e1f015268c7c34cba","parameters":[{"type":"Signature"},{"type":"Signature"}],"signatures":{"036f9a8087d0dc64b5161a15dd02faad1a729c5ba7048f3bc60cee0138aa3e1f01":"4b042ffe52d6a3382de97fcb6c7ddf6b8f2ea81f2f91bd8163f506b25ad91f9216155f31e382ec97d6be7ef887d77b05844fd45098ac145a623bbc93d9245e58"}}}}                                                                                                                           Signed Output:                                                                                                                                                                                      {"type":"Neo.Network.P2P.Payloads.Transaction","hex":"0071c5de327d320be117004bb473cd7db0d1dc7550f20e144700e1f505000000000cfd2300000000009515200000017d320be117004bb473cd7db0d1dc7550f20e14470151551420d007c675446161dbc0c833f83410d3accb3eeb147d320be117004bb473cd7db0d1dc7550f20e144753c1087472616e736665721415caa04214310670d5e5a398e147e0dbed98cf4368627d5b52f1","items":{"0x47140ef25075dcd1b07dcd73b44b0017e10b327d":{"script":"522102166b93d66306d106a85caa02c4d36b72f85e7db69e324f4989ecea696d87f5e421036f9a8087d0dc64b5161a15dd02faad1a729c5ba7048f3bc60cee0138aa3e1f015268c7c34cba","parameters":[{"type":"Signature","value":"4b042ffe52d6a3382de97fcb6c7ddf6b8f2ea81f2f91bd8163f506b25ad91f9216155f31e382ec97d6be7ef887d77b05844fd45098ac145a623bbc93d9245e58"},{"type":"Signature","value":"3312d74b
```

**Comment by cloud8little** [comment]
@shargon could you help look into this issue since now RpcClient is under development?  If you have higher priority, then this one can be downgraded a bit.

**Comment by shargon** [comment]
I need to solve this first (https://github.com/neo-project/neo-node/issues/510) for doing all of this steps

**Comment by superboyiii** [comment]
@shargon Will you go on this?

**Comment by shargon** [comment]
I want to fix this this week

**Comment by shargon** [comment]
Could you check if it persist, my test has a different format.

```
HTTP/1.1 200 OK
Connection: close
Date: Wed, 11 Mar 2020 17:13:09 GMT
Content-Type: application/json
Server: Kestrel
Vary: Accept-Encoding
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: GET, POST
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 31536000
Content-Length: 329

{"jsonrpc":"2.0","id":1,"result":{"type":"Neo.Network.P2P.Payloads.Transaction","hex":"ACS8pHnvGWfW9M0G\u002B0w\u002B9xn2qfW2pSyYVgDh9QUAAAAAQiEkAAAAAACAFCAAAAHvGWfW9M0G\u002B0w\u002B9xn2qfW2pSyYVgFVEQwU7xln1vTNBvtMPvcZ9qn1tqUsmFYMFO8ZZ9b0zQb7TD73Gfap9balLJhWE8AMCHRyYW5zZmVyDBSJdyDYzXb08Aq/o3wO3YicII/em0FifVtSOQ==","items":{}}}
```

**Comment by superboyiii** [comment]
> Could you check if it persist, my test has a different format.
> 
> ```
> HTTP/1.1 200 OK
> Connection: close
> Date: Wed, 11 Mar 2020 17:13:09 GMT
> Content-Type: application/json
> Server: Kestrel
> Vary: Accept-Encoding
> Access-Control-Allow-Headers: Content-Type
> Access-Control-Allow-Methods: GET, POST
> Access-Control-Allow-Origin: *
> Access-Control-Max-Age: 31536000
> Content-Length: 329
> 
> {"jsonrpc":"2.0","id":1,"result":{"type":"Neo.Network.P2P.Payloads.Transaction","hex":"ACS8pHnvGWfW9M0G\u002B0w\u002B9xn2qfW2pSyYVgDh9QUAAAAAQiEkAAAAAACAFCAAAAHvGWfW9M0G\u002B0w\u002B9xn2qfW2pSyYVgFVEQwU7xln1vTNBvtMPvcZ9qn1tqUsmFYMFO8ZZ9b0zQb7TD73Gfap9balLJhWE8AMCHRyYW5zZmVyDBSJdyDYzXb08Aq/o3wO3YicII/em0FifVtSOQ==","items":{}}}
> ```

Due to my test, the incompleted signature context from RPC could be signed and relayed in neo-cli and it works well. But they're a little different in content. For example, I made a transaction from cli:
```
neo> create wallet multi.json                                                                                           password: *
password: *
address: NdEx1yyEP84AuTky49cwJxGuWP3UYSNHRg                                                                              pubkey: 0333b24ee50a488caa5deec7e021ff515f57b7993b93b45d7df901e23ee3004916
neo> open wallet owen.json                                                                                              password: *
neo> list key                                                                                                           03b9c46c6d5c671ef5c21bc7aa7c30468aeb081a2e3895269adf947718d650ce1e                                                      031de3df8fdb4033a17b4b32b2bb844e8d39b998d9e4b913a637e729d982bcf9bf
neo> import multisigaddress 2 0333b24ee50a488caa5deec7e021ff515f57b7993b93b45d7df901e23ee3004916 03b9c46c6d5c671ef5c21bc7aa7c30468aeb081a2e3895269adf947718d650ce1e                                                                             Multisig. Addr.: NdEvVjeptcWDv7fvPyo87e5HQssiJwpxU4
neo> send gas NdEvVjeptcWDv7fvPyo87e5HQssiJwpxU4 1000
password: *
TXID: 0x2a34f9198abfeecd49f8078b2296f9274d14bf83c979b34bf30821e81e2dd42f
neo> open wallet multi.json
password: *
neo> import multisigaddress 2 0333b24ee50a488caa5deec7e021ff515f57b7993b93b45d7df901e23ee3004916 03b9c46c6d5c671ef5c21bc7aa7c30468aeb081a2e3895269adf947718d650ce1e                                                                             Multisig. Addr.: NdEvVjeptcWDv7fvPyo87e5HQssiJwpxU4
neo> list asset
NdEx1yyEP84AuTky49cwJxGuWP3UYSNHRg
NEO: 0
GAS: 0

NdEvVjeptcWDv7fvPyo87e5HQssiJwpxU4
NEO: 0                                                                                                                  GAS: 1000
----------------------------------------------------
Total:   NEO: 0    GAS: 1000                                                                                                                                                                                                                    NEO hash: 0x9bde8f209c88dd0e7ca3bf0af0f476cdd8207789
GAS hash: 0x8c23f196d8a1bfd103a9dcb1f9ccf0c611377d3b
neo> send gas NdEvVjeptcWDv7fvPyo87e5HQssiJwpxU4 100                                                                    password: *                                                                                                             
SignatureContext:                                                                                                       {"type":"Neo.Network.P2P.Payloads.Transaction","hex":"APV/zh6\u002BD8vNZed5xSsY3Osh9CcAilKo5ADh9QUAAAAAgkAkAAAAAACWIyAAAAG\u002BD8vNZed5xSsY3Osh9CcAilKo5AFdAwDkC1QCAAAADBS\u002BD8vNZed5xSsY3Osh9CcAilKo5AwUvg/LzWXnecUrGNzrIfQnAIpSqOQTwAwIdHJhbnNmZXIMFDt9NxHG8Mz5sdypA9G/odiW8SOMQWJ9W1I5","items":{"0xe4a8528a0027f421ebdc182bc579e765cdcb0fbe":{"script":"EgwhAzOyTuUKSIyqXe7H4CH/UV9Xt5k7k7RdffkB4j7jAEkWDCEDucRsbVxnHvXCG8eqfDBGiusIGi44lSaa35R3GNZQzh4SC0Ewc7O7","parameters":[{"type":"Signature"},{"type":"Signature"}],"signatures":{"0333b24ee50a488caa5deec7e021ff515f57b7993b93b45d7df901e23ee3004916":"bAhbpx1J8eIPLb5\u002BfvDIRQTbX0doilPxQO\u002BQKS\u002B3fpgyjTwV73UPrv0qsb6I3ZuQjfCA7xoePl5rU508B7k\u002B7w=="}}}}
neo>
```
And what I get from Rpc is :
{"type":"Neo.Network.P2P.Payloads.Transaction","hex":"ABrGqCa\u002BD8vNZed5xSsY3Osh9CcAilKo5ADh9QUAAAAAgkAkAAAAAADPIyAAAAG\u002BD8vNZed5xSsY3Osh9CcAilKo5AFdAwDkC1QCAAAADBS\u002BERDxf2rX7tOZvvuUAv3/X2Q2vAwUvg/LzWXnecUrGNzrIfQnAIpSqOQTwAwIdHJhbnNmZXIMFDt9NxHG8Mz5sdypA9G/odiW8SOMQWJ9W1I5","items":{"0xe4a8528a0027f421ebdc182bc579e765cdcb0fbe":{"script":"EgwhAzOyTuUKSIyqXe7H4CH/UV9Xt5k7k7RdffkB4j7jAEkWDCEDucRsbVxnHvXCG8eqfDBGiusIGi44lSaa35R3GNZQzh4SC0Ewc7O7","parameters":[{"type":"Signature"},{"type":"Signature"}],"signatures":{"0333b24ee50a488caa5deec7e021ff515f57b7993b93b45d7df901e23ee3004916":"B5X0jU51KEQaKlcu33FI4LkT2QUZGdj0EhPTz6D8jWmKN/Q/psaLjOMwciOXKcsTm/IBrMXYBGsyngJ9wfrY3g=="}}}}

As you see `"B5X0jU51KEQaKlcu33FI4LkT2QUZGdj0EhPTz6D8jWmKN/Q/psaLjOMwciOXKcsTm/IBrMXYBGsyngJ9wfrY3g=="` and `bAhbpx1J8eIPLb5\u002BfvDIRQTbX0doilPxQO\u002BQKS\u002B3fpgyjTwV73UPrv0qsb6I3ZuQjfCA7xoePl5rU508B7k\u002B7w==` is absolutely different.

Anyway, finally I could relay it from both type.
```
neo> open wallet owen.json
password: *
neo> sign {"type":"Neo.Network.P2P.Payloads.Transaction","hex":"ABrGqCa\u002BD8vNZed5xSsY3Osh9CcAilKo5ADh9QUAAAAAgkAkAAAAAADPIyAAAAG\u002BD8vNZed5xSsY3Osh9CcAilKo5AFdAwDkC1QCAAAADBS\u002BERDxf2rX7tOZvvuUAv3/X2Q2vAwUvg/LzWXnecUrGNzrIfQnAIpSqOQTwAwIdHJhbnNmZXIMFDt9NxHG8Mz5sdypA9G/odiW8SOMQWJ9W1I5","items":{"0xe4a8528a0027f421ebdc182bc579e765cdcb0fbe":{"script":"EgwhAzOyTuUKSIyqXe7H4CH/UV9Xt5k7k7RdffkB4j7jAEkWDCEDucRsbVxnHvXCG8eqfDBGiusIGi44lSaa35R3GNZQzh4SC0Ewc7O7","parameters":[{"type":"Signature"},{"type":"Signature"}],"signatures":{"0333b24ee50a488caa5deec7e021ff515f57b7993b93b45d7df901e23ee3004916":"B5X0jU51KEQaKlcu33FI4LkT2QUZGdj0EhPTz6D8jWmKN/Q/psaLjOMwciOXKcsTm/IBrMXYBGsyngJ9wfrY3g=="}}}}
Signed Output:
{"type":"Neo.Network.P2P.Payloads.Transaction","hex":"ABrGqCa\u002BD8vNZed5xSsY3Osh9CcAilKo5ADh9QUAAAAAgkAkAAAAAADPIyAAAAG\u002BD8vNZed5xSsY3Osh9CcAilKo5AFdAwDkC1QCAAAADBS\u002BERDxf2rX7tOZvvuUAv3/X2Q2vAwUvg/LzWXnecUrGNzrIfQnAIpSqOQTwAwIdHJhbnNmZXIMFDt9NxHG8Mz5sdypA9G/odiW8SOMQWJ9W1I5","items":{"0xe4a8528a0027f421ebdc182bc579e765cdcb0fbe":{"script":"EgwhAzOyTuUKSIyqXe7H4CH/UV9Xt5k7k7RdffkB4j7jAEkWDCEDucRsbVxnHvXCG8eqfDBGiusIGi44lSaa35R3GNZQzh4SC0Ewc7O7","parameters":[{"type":"Signature","value":"vRz4Lxf7L1SXLvPbm/DNTvLYP0y8AADyLlqpcw4qGkvDm8icd4SjeSQxTsxrwWLZDOtlmsx1zHkE19BW8aqzvQ=="},{"type":"Signature","value":"B5X0jU51KEQaKlcu33FI4LkT2QUZGdj0EhPTz6D8jWmKN/Q/psaLjOMwciOXKcsTm/IBrMXYBGsyngJ9wfrY3g=="}]}}}
neo> relay {"type":"Neo.Network.P2P.Payloads.Transaction","hex":"ABrGqCa\u002BD8vNZed5xSsY3Osh9CcAilKo5ADh9QUAAAAAgkAkAAAAAADPIyAAAAG\u002BD8vNZed5xSsY3Osh9CcAilKo5AFdAwDkC1QCAAAADBS\u002BERDxf2rX7tOZvvuUAv3/X2Q2vAwUvg/LzWXnecUrGNzrIfQnAIpSqOQTwAwIdHJhbnNmZXIMFDt9NxHG8Mz5sdypA9G/odiW8SOMQWJ9W1I5","items":{"0xe4a8528a0027f421ebdc182bc579e765cdcb0fbe":{"script":"EgwhAzOyTuUKSIyqXe7H4CH/UV9Xt5k7k7RdffkB4j7jAEkWDCEDucRsbVxnHvXCG8eqfDBGiusIGi44lSaa35R3GNZQzh4SC0Ewc7O7","parameters":[{"type":"Signature","value":"vRz4Lxf7L1SXLvPbm/DNTvLYP0y8AADyLlqpcw4qGkvDm8icd4SjeSQxTsxrwWLZDOtlmsx1zHkE19BW8aqzvQ=="},{"type":"Signature","value":"B5X0jU51KEQaKlcu33FI4LkT2QUZGdj0EhPTz6D8jWmKN/Q/psaLjOMwciOXKcsTm/IBrMXYBGsyngJ9wfrY3g=="}]}}}
Data relay success, the hash is shown as follows:
0x92de2c1d06a12fd634a7a45803131a2192d3bfb1aad891816a9e16bea3133a5d
```

**Comment by superboyiii** [comment]
Oh, I think it's because of nonce! I'll close this. @shargon
