### ISSUE TITLE
Change repo name to `neo-modules`

### ISSUE THREAD

**Issue by erikzhang** [neo-project/neo-modules#162]
What do you think? @neo-project/core

**Comment by shargon** [comment]
Is good to me

**Comment by lock9** [comment]
I think it is good too, this way we can put the RPC client here.

**Comment by erikzhang** [comment]
Done.

**Comment by hal0x2328** [comment]
There has already been an existing NeoModules project in the CoZ repo since 2018. I think that this will cause unnecessary developer confusion.
