### ISSUE TITLE
create Restful and GraphQL servers

### ISSUE THREAD

**Issue by bettybao1209** [neo-project/neo-modules#168]
Since the RpcServer has been ported to the module repo by Erik, maybe it's the time to pick up the Restful and GraphQL servers (https://github.com/neo-project/neo/issues/996). 

>REST update (#726) :
> - [ ] Create swagger documentation (#1003)
> - [ ] Add REST uri endpoints (#1004 )
> - [ ] Update error messages (#975)
> - [ ] Update SDK to use REST API
> - [ ] Add REST API section to the documentation

>GraphQL update (#623) :
>  - [ ] Create GraphQL schema
> - [ ] Update data serialization methods
 > - [ ] Add GraphQL endpoint
 > - [ ] Update SDK to support GraphQL
 > - [ ] Add GraphQL section to the documentation

Any advice would be great. If possible,  we'll submit these PRs.

**Comment by vncoelho** [comment]
We had such discussion with @jsolman some time ago: https://github.com/neo-project/neo/issues/623

But the idea did not moved to much forward at that time.

**Comment by bettybao1209** [comment]
hi @vncoelho，the RestPlugin and GraphQL plugin are all available at the ngd repo  https://github.com/neo-ngd/neo-common-plugins.
