### ISSUE TITLE
RocksDB Building error

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#173]
```cs
Plugins/Storage/RocksDBStore.cs(10,30): error CS0507: 'RocksDBStore.Configure()': cannot change access modifiers when overriding 'protected' inherited member 'Plugin.Configure()' [/opt/neo-plugins/src/RocksDBStore/RocksDBStore.csproj]
```

@shargon, do you have an idea?

**Comment by shargon** [comment]
I will take a look

**Comment by shargon** [comment]
Where did you get this error?

**Comment by vncoelho** [comment]
We are adjusting our script for automatic releasing a neo-cli with specific commits.

This error was obtained when building the plugins.
Something around here:
`dotnet publish /opt/neo-plugins/src/$PLUGIN_TO_INCLUDE/$PLUGIN_TO_INCLUDE.csproj -o $PLUGIN_TO_INCLUDE -c Release`

**Comment by vncoelho** [comment]
https://github.com/NeoResearch/neo-tests/blob/master/docker-build-neo-cli/building_scripts/build_plugin_3x.sh#L31

**Comment by shargon** [comment]
RocksDBStore has no Configure method, which branch did you use?

**Comment by vncoelho** [comment]
aheuahuea, everything was on master, @shargon.
This line crashed: https://github.com/neo-project/neo-modules/blob/c08ce9017ea62ef59ec69136005d40fda642537b/src/RocksDBStore/Plugins/Storage/RocksDBStore.cs#L10
