### ISSUE TITLE
[RpcNep5Tracker] Shall we add auto-claim gas history to the method getnep5transfers

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-modules#176]
**Description**:
when call getnep5transfers, auto-claim gas history not shown in the response. while it shows in the method getapplicationlog.
**Reproduction steps**:
Env: neo-node: a137b6f20c957706cfbbea323e2a1d18e8c79a14
neo: 3.0.0-CI00844
RpcNep5Tracker/applicationlog: c08ce9017ea62ef59ec69136005d40fda642537b
win10 x64
1. Build neo-node/rpcnep5tracker/applicationlog
2. Start a single consensus node.
3. Withdraw the Genesis Neo/GAS.
4. Send it to wallet from.json
5. open wallet from.json and wait for several blocks.
6. send 2 neo/3 gas to wallet test1.json
7. call getnep5tracker/getapplicationlog.

**Suggestion**:
From users perspective, it is better to have the history for the method getnep5transfers, and thought that is what the plugin aims to implement. Besides preview1 supported the function too. 

`{
  "jsonrpc": "2.0",
  "method": "getapplicationlog",
  "params": ["0xb1f1f85392d179084caf1b4b56916a6942f713212d2047300b3bef059f0c2dd3"],
  "id": 1
}`

`{
  "jsonrpc": "2.0",
  "method": "getnep5transfers",
  "params": ["NX25qcUMBRBgAx4bcjrkNc4Tj6GWjqJVeD"],
  "id": 1
}
`
Response:
[Uploading rpcResponse.zip…]()

**Comment by vncoelho** [comment]
Good point, @cloud8little.

I am not sure if it is a real `Nep5Transfer` or we should list it in a different call.
But I am ok if it comes together with the list of NEP5.

**Comment by cloud8little** [comment]
close this because it is already fixed.
