### ISSUE TITLE
[RpcNep5Tracker]Getnep5balances, balance won't change when a transaction is not `transfer`. 

### ISSUE THREAD

**Issue by nicolegys** [neo-project/neo-modules#179]
Describe the bug
Getnep5balances, balance won't change when a tx is not transfer. Then, make a transfer tx, the gas balance value will return to normal.

To Reproduce
1.open wallet 6.json, deploy a smartcontract, list asset, gas balance = 8.9850761
![image](https://user-images.githubusercontent.com/43694095/72419520-f65c2c00-37b7-11ea-96bd-dd9ce8d51320.png)

2.rpc getnep5balances, gas balance didn't change, gas balance = 10
![image](https://user-images.githubusercontent.com/43694095/72419617-23a8da00-37b8-11ea-9c5e-5173025bc383.png)

3.make a transfer transaction, list asset, gas balance = 6.9723922
![image](https://user-images.githubusercontent.com/43694095/72419641-2c99ab80-37b8-11ea-9960-6d0b9e3dd38f.png)

4.rpc getnep5balances, gas balance changed, gas balance = 6.9723922
![image](https://user-images.githubusercontent.com/43694095/72419664-3ae7c780-37b8-11ea-9941-87bd005f014b.png)

**Comment by nicolegys** [comment]
@Tommo-L :)

**Comment by Tommo-L** [comment]
Got, we'll fix it
