### ISSUE TITLE
getbalance isn't able to return value when invoking non-native nep5 sc

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-modules#182]
I deployed an nep5 sc and it works well when making transaction and RpcNepTracker is able to catch its balance and transaction record. Then I made a wallet with two addresses. One has nep5 asset, the other is a clean address. However when I tried to invoke `getbalance` via RPC, it always return 0 on value . Then I made a single-address wallet within nep5 asset, it did return correct value. And when I invoke native sc (neo and gas), it always returns correct value. I think there might be some issues happened when balance=0 (Maybe it doesn't return 0 but null).
![image](https://user-images.githubusercontent.com/38493437/72869211-77b73f80-3d1f-11ea-8aae-e9afe227e73d.png)

**Comment by bettybao1209** [comment]
![image](https://user-images.githubusercontent.com/12050350/75767789-50bc4680-5d7e-11ea-8fb1-09922dfe050a.png)
The `balanceOf` method in my nep5 sc can output the result correctly. I think the issue may be caused here.
