### ISSUE TITLE
Ship neo modules binaries via nuget

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#202]
At some point, binaries in this repo need to be delivered via NuGet. They can also be delivered via github releases tab, but they need to be available via nuget in order to support scenarios like 3rd party RpcServer plugins or RpcClient based applications.

**Comment by shargon** [comment]
Agree, also it will be good for versioning

**Comment by wanglongfei88** [comment]
Agree, vote for it

**Comment by vncoelho** [comment]
I believe that this might be good, better if automatic with github releases.

**Comment by devhawk** [comment]
@superboyiii any chance we can do this as part of preview 4?

**Comment by devhawk** [comment]
FYI, https://github.com/neo-project/neo-modules/pull/403 will make it easy to update neo CI build version across all modules + standardizes package names

**Comment by devhawk** [comment]
Now that we've shipped preview 4, can we publish the following packages from this repo:

* ApplicationLogs
* LevelDBStore
* RpcClient   
* RpcNep17Tracker
* RpcServer

**Comment by devhawk** [comment]
ping @erikzhang @Tommo-L @superboyiii

**Comment by devhawk** [comment]
As of 2021-09-15, RpcClient, RpcServer and Consensus plugins are shipping on NuGet. Can we also add Oracles and State service?

**Comment by devhawk** [comment]
we've been doing this for a while now, but never closed this issue
