### ISSUE TITLE
RpcServer plugin needs to be programmatically configurable

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#203]
neo-express will need to programmatically create and configure the RpcServer plugin w/o depending on config.json file.

**Comment by vncoelho** [comment]
Agree @devhawk, in the way it is right now we need a manual configuraiton that requires external workarounds.

**Comment by devhawk** [comment]
I will prototype something out as part of my neo-express for neo 3 work and submit a PR

**Comment by vncoelho** [comment]
Very good, @devhawk. That will surely be a nice PR and will help the setup of several RPC clients and privatenets.
