### ISSUE TITLE
RpcServer does not compile against neo master branch

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#205]
RpcServer.Node.cs(44,47): error CS0246: The type or namespace name 'RelayResultReason' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\harry\Source\neo\official\modules\src\RpcServer\RpcServer.csproj]

**Comment by vncoelho** [comment]
Check this branch: https://github.com/neo-project/neo-modules/pull/200

**Comment by devhawk** [comment]
I think the issue is that RelayResultReason was renamed VerifyResult. @vncoelho can you verify this?

**Comment by vncoelho** [comment]
Check the PR I mentioned above. It is already solved there.
It is now an eventstream of akka as well.

**Comment by devhawk** [comment]
Will that PR be merged before preview 2?
