### ISSUE TITLE
RpcClient needs to support async versions of RPC wrapper methods 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#209]
For example, WalletApi.Transfer needs a WalletApi.TransferAsync counterpart

**Comment by chenquanyu** [comment]
We can change all the methods in `RpcClient` to `async`, but now the methods in `Neo` are `sync`. Shall we keep both versions of them? @erikzhang @shargon

**Comment by shargon** [comment]
I don't like async methods :P, I prefer both, but not only async

**Comment by devhawk** [comment]
any async call can be waited synchronously via the Task.Result property. Since HttpClient doesn't provide sync methods, RpcClient.Send method [uses Result property](https://github.com/neo-project/neo-modules/blob/master/src/RpcClient/RpcClient.cs#L83) to make it a synchronous call. 

Instead of parallel sync/async implementations, wouldn't it make more sense to have a single set of async methods? Folks that want to synchronously wait on the result can simply use the Result property.
