### ISSUE TITLE
WalletAPI.Transfer does not work for sending from genesis account

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#210]
Attempting to send 1000 neo from genesis account to a standard address using a single node Neo3 chain (master branch). The consensus node wallet has two accounts, the node-specific account (`NU78azX2nqbuDPthu5UGMaCXTVwpAkpvye`) and the multi-sig account (`NfC9EW6UJEbfX4TKCnqGf72AKHXUfR71ma`). I am calling GetKey() on the multi-sig WalletAccount and passing it to WalletApi.Transfer. Transfer throws an exception `Insufficient GAS in address: NU78azX2nqbuDPthu5UGMaCXTVwpAkpvye`. That is the node-specific account address, NOT the multi-sig account address.

Stepping thru the transfer function, the exception is throwing in the TransactionManager.Sign() function. Sign is checking the gas balance, finding the gas balance to be zero and throwing.

**Comment by chenquanyu** [comment]
Hi @devhawk 
The `WalletApi.Transfer` is not ready for transferring assets from a multi-sig account now. You may refer to this document to [construct a transaction](https://github.com/neo-project/docs/blob/release-neo3/docs/en-us/tooldev/sdk/transaction.md).

**Comment by devhawk** [comment]
Thanks @chenquanyu, I'll give that a try.

**Comment by devhawk** [comment]
@chenquanyu I tried to follow the [guidance you provided](https://github.com/neo-project/docs/blob/release-neo3/docs/en-us/tooldev/sdk/transaction.md#constructing-a-transaction-to-transfer-from-multi-signature-account) (with a local patch for #223) but SendRawTransaction throws an "Invalid" exception.
