### ISSUE TITLE
 CheckWitness on invokefunction

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-modules#212]
port to Neo3 https://github.com/neo-project/neo/pull/1418

**Comment by chenquanyu** [comment]
![image](https://user-images.githubusercontent.com/4393234/78341976-2521bb80-75cb-11ea-8f79-2d15849ddfa5.png)

**Comment by gsmachado** [comment]
Hello @Tommo-L
Can you please review this pull request and merge it?

**Comment by gsmachado** [comment]
Also, @Tommo-L, can you provide us an example of the updated JSON-RPC call (including the additional param value)?

**Comment by Tommo-L** [comment]
> Can you please review this pull request and merge it?

It'll be merged soon.

> considering the PR, can you provide us an example of the updated JSON-RPC call (including the additional param value)?

Since preview2 will be released, we'll update our documentation in official website, asap.
