### ISSUE TITLE
SendRawTransaction RPC Method hangs 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#216]
SendRawTransaction RPC method submits the provided tx to the blockchain via [Blockchain.Ask](https://github.com/neo-project/neo-modules/blob/master/src/RpcServer/RpcServer.Node.cs#L73). However, Blockchain.OnReceive [does not respond with Sender.Tell (in master branch)](https://github.com/neo-project/neo/blob/master/src/neo/Ledger/Blockchain.cs#L458). So the SendRawTransaction RPC method never returns

**Comment by erikzhang** [comment]
#200

**Comment by devhawk** [comment]
#200 has been closed. Is there a new PR that will fix this issue?

**Comment by bettybao1209** [comment]
> #200 has been closed. Is there a new PR that will fix this issue?
Yes, please refer to PR https://github.com/neo-project/neo-modules/pull/220

**Comment by devhawk** [comment]
This appears to be fixed by neo 3 preview 2
