### ISSUE TITLE
TransactionManager.MakeTransaction throws exception

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#223]
Attempting to implement [transfer from multi-sig account](https://github.com/neo-project/docs/blob/release-neo3/docs/en-us/tooldev/sdk/transaction.md#constructing-a-transaction-to-transfer-from-multi-signature-account). TransactionManager.MakeTransaction throws an exception: `Exception thrown: 'Neo.Network.RPC.RpcException' in RpcClient.dll: 'Unable to cast object of type 'Neo.IO.Json.JString' to type 'Neo.IO.Json.JArray'.'`

It appears that RpcClient.InvokeScript is encoding the parameters incorrectly.  [RpcServer `invokescript`](https://github.com/neo-project/neo-modules/blob/d62b18bcea99186614c3043603fcaa8e6214ba77/src/RpcServer/RpcServer.SmartContract.cs#L89) looks like it's expecting CheckWitnessHashes to be an array of it's own while RpcClient.InvokeScript is simply appending the witness hashes to the parameter array

**Comment by devhawk** [comment]
Suggestion for fix:

``` csharp
public RpcInvokeResult InvokeScript(byte[] script, params UInt160[] scriptHashesForVerifying)
{
    var hashes = new JArray(scriptHashesForVerifying.Select(p => (JString)p.ToString()));
    var parameters = new JObject[] { script.ToHexString(), hashes };
    return RpcInvokeResult.FromJson(RpcSend("invokescript", parameters));
}
```

**Comment by wanglongfei88** [comment]
@chenquanyu can you please take a look at this issue ?
