### ISSUE TITLE
Move SystemLog to a neo-cli command

### ISSUE THREAD

**Issue by shargon** [neo-project/neo-modules#228]
I think that we should be able to enable/disable the log output by commands.

`log true`
`log false`

Also I think that this shouldn't be a plugin.

**Comment by Tommo-L** [comment]
Agree

**Comment by erikzhang** [comment]
I don't think it is necessary to move to the core. Others can implement their own log plug-ins, such as saving logs to the database.

**Comment by Tommo-L** [comment]
It's not move to the core, it's just move systemlog into neo-cli, neo-cli can implement the log plugin by default.

**Comment by joeqian10** [comment]
Where do you suggest to put the configuration of the logger? In a separate config file or add a section in the config.json of neo-cli as shown below? 
```json
{
  "ApplicationConfiguration": {
    "Logger": {
      "Path": "SystemLogs_{0}",
      "ConsoleOutput": true
    },
    "Storage": {
      "Engine": "LevelDBStore"
    },
    "P2P": {
      "Port": 10333,
      "WsPort": 10334
    },
    "UnlockWallet": {
      "Path": "",
      "Password": "",
      "StartConsensus": false,
      "IsActive": false
    },
    "PluginURL": "https://github.com/neo-project/neo-modules/releases/download/v{1}/{0}.zip"
  }
}
```

**Comment by Tommo-L** [comment]
It's ok for me. plz, set `ConsoleOutput` default `false`. And you need to add `log` command.

**Comment by joeqian10** [comment]
The PR to fix this is [582](https://github.com/neo-project/neo-node/pull/582). @shargon @Tommo-L @erikzhang please take a look 😄

**Comment by joeqian10** [comment]
> I don't think it is necessary to move to the core. Others can implement their own log plug-ins, such as saving logs to the database.

Maybe we should rename SystemLog plugin to make it as a sample logger for other developers, or we can just delete it.

**Comment by superboyiii** [comment]
@erikzhang What's your opinion?

**Comment by erikzhang** [comment]
Just remove it.
