### ISSUE TITLE
GetUnclaimedGas Generic

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#241]
Perhaps we need extra calls on RPCServer  plugin such as generic `GetUnclaimedGas` call apart of just the the one linked to the wallet itself: https://github.com/neo-project/neo-modules/blob/d62b18bcea99186614c3043603fcaa8e6214ba77/src/RpcServer/RpcServer.Wallet.cs#L71-L81

The one linked to the account should be something like `GetWalletUnclaimedGas`

**Comment by roman-khimov** [comment]
IMO this call should just be extended to work with any addresses, getting this data is so cheap on Neo 3 that limiting this method to wallet-only addresses makes no sense to me. And I don't think we need two methods here, one working for any address is enough.

In fact, that's the model neo-go uses for `getunclaimed` on Neo 2, answering this call for any addresses known to the chain and it works fine (even though it costs something in terms of additional UTXO tracking).

**Comment by vncoelho** [comment]
Agree with you @roman-khimov
