### ISSUE TITLE
UnlockWallet Active is not triggering RPCServer

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#242]
The config that activate wallet is not loading the RPCServer wallet
https://github.com/neo-project/neo-node/blob/4bfce3d9e3d6afaed34aefef9396f148682dbb70/neo-cli/CLI/MainService.cs#L412

, which is kept as `null` https://github.com/neo-project/neo-modules/blob/3dcd2bdac59611ad5c71fcb4891f631919892d0a/src/RpcServer/RpcServer.Wallet.cs#L30

Perhaps it should be loaded, otherwise a manual RPC call `openwallet` needs to be done.

**Comment by erikzhang** [comment]
This is a protection.
