### ISSUE TITLE
 Difference between implementation and documentation of GetVersion RPC method

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo-modules#261]
**Describe the bug**
Implementation of [`GetVersion`](https://github.com/neo-project/neo-modules/blob/master/src/RpcServer/RpcServer.Node.cs#L60) RPC method assumes lover-cased underscored JSON fields `tcp_port`, `ws_port` and `user_agent`. Documentation [example](https://docs.neo.org/v3/docs/en-us/reference/rpc/latest-version/api/getversion.html) differs from that and describes `tcpPort`, `wsPort` and `useragent`.

**Expected behavior**
Documentation should match implementation.

**Comment by joeqian10** [comment]
I think we need to change the documentation, not the code.

**Comment by Tommo-L** [comment]
I think we'd better keep consistent by camel case, update code first(both method name and result), then documentation.

As you can see, there are two different styles in our json rpc.

**getblock**
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "hash": "0x4c1e879872344349067c3b1a30781eeb4f9040d3795db7922f513f6f9660b9b2",
    "size": 686,
    "version": 0,
    "previousblockhash": "0x53ce15a53a184faa058be9008ece887d7f0b30a459342ce42753f73f9ed390e9",
    "merkleroot": "0x9c909e1e3ba03290553a68d862e002c7a21ba302e043fc492fe069bf6a134d29",
    "time": 1476834896,
    "index": 10000,
    "nonce": "aa2c0fd5dc445445",
    "nextconsensus": "APyEx5f4Zm4oCHwFWiSTaph1fPBxZacYVR",
    "script": {
      "invocation": "405e31eb19b1feaeb27c35a6de4d8884794291fc6cebd77158954ef03b10d5d0a30b52bc9",
      "verification": "552102486fd15702c4489509357ae"
    },
    "tx": [
      {
        "txid": "0x9c909e1e3ba03290553a68d862e002c7a21ba302e043fc492fe069bf6a134d29",
        "size": 10,
        "type": "MinerTransaction",
        "version": 0,
        "attributes":[],
        "vin":[],
        "vout":[],
        "sys_fee": "0",
        "net_fee": "0",
        "scripts":[],
        "nonce": 3695465541
      }
   ],
    "confirmations": 981987,
    "nextblockhash": "0xc9a32cd215837c02dd72613bfad6ed064579e77bafd859907f87b3e67fa498cc"
  }
}
```

**Comment by joeqian10** [comment]
> I think we'd better keep consistent by camel case, update code first(both method name and result), then documentation.

I'm ok with any case style, and we need to make a decision, then we stick to the standard.

**Comment by joeqian10** [comment]
@erikzhang @shargon Please let us know which case style you prefer, and I will make the change.

**Comment by erikzhang** [comment]
I like all lowercase. But I can accept other styles.

**Comment by shargon** [comment]
I like camelcase

**Comment by joeqian10** [comment]
> I like all lowercase. But I can accept other styles.
> I like camelcase

OK, then snake case will be used.🤣
