### ISSUE TITLE
[RpcServer] Nep6 wallet with non-json extension should be supported

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-modules#263]
**Describe the bug**
In RpcServer: 
https://github.com/neo-project/neo-modules/blob/c51b96bb8802f48a14e2677a027bed408a0a5b26/src/RpcServer/RpcServer.Wallet.cs#L121-L136
only wallet file with extension ".db3" and ".json" is supported, otherwise throw exception. 

While for neo-node project, the logic is a little different, for nep6 wallet, it can support any extension.
https://github.com/neo-project/neo-node/blob/ba5e3eaac3885bf222c1ef764be564a2f28615d7/neo-cli/CLI/MainService.cs#L321-L329

```cs
            if (Path.GetExtension(path) == ".db3")
            {
                CurrentWallet = UserWallet.Open(path, password);
            }
            else
            {
                NEP6Wallet nep6wallet = new NEP6Wallet(path);
                nep6wallet.Unlock(password);
                CurrentWallet = nep6wallet;
```

**To Reproduce**
1. Create a nep6 wallet name 1.json
2. change password with a new password
3. check if 1.json.bak generated.
4. open wallet 1.json.bak with the old password.
5. return error "Specified method is not supported."

**Expected behavior**
It should return true.

**Screenshots**

**Platform:**
 - OS: Windows 10 x64/linux

![c17d2a460fd3a5c4430b1a8b63492a8](https://user-images.githubusercontent.com/34291844/84886872-926fc380-b0c7-11ea-94c9-be0e2f5f5de1.png)
![2178bb1f55ae82c22e43022b144224a](https://user-images.githubusercontent.com/34291844/84886878-94398700-b0c7-11ea-96bc-bd63b4320d7f.png)

**Comment by shargon** [comment]
I think that it should be `json`, not any.
