### ISSUE TITLE
Add event name in NotifyEventArgs

### ISSUE THREAD

**Issue by Tommo-L** [neo-project/neo-modules#265]
Apply https://github.com/neo-project/neo/pull/1701

- Update Nep5Tracker plugin
   - Add `eventName` field in NotifyEventArgs

**Comment by joeqian10** [comment]
Shall we also modify other places where NotifyEventArgs are used? For example, in LogReader.cs:
![image](https://user-images.githubusercontent.com/33386299/85353642-53b09200-b53b-11ea-9859-fa936b4a656f.png)

**Comment by joeqian10** [comment]
@erikzhang @shargon @Tommo-L I can fix and close this issue first, and modify those places in later PRs. How do you like it?

**Comment by Tommo-L** [comment]
One pr is enough.
