### ISSUE TITLE
RpcClient.CalculateNetworkFee no longer compiles against neo master branch

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#311]
Wallet.CalculateNetworkFee signature has changed.

**Comment by ProDog** [comment]
That changed in https://github.com/neo-project/neo/pull/1800/files#diff-bac7c9fe6b52541341827f089612cfeaL356-L399;
RpcClient need calculate network fee in https://github.com/neo-project/neo-modules/blob/master/src/RpcClient/TransactionManager.cs#L105
@shargon do you have any ideas?😀

**Comment by shargon** [comment]
```csharp
public TransactionManager Sign()
        {
            // Calculate NetworkFee
            Tx.NetworkFee = Wallet.CalculateNetworkFee(Blockchain.Singleton.GetSnapshot(), Tx);
            var gasBalance = nep5API.BalanceOf(NativeContract.GAS.Hash, Tx.Sender);
        
...
```
?

**Comment by ProDog** [comment]
It's good, but now `Wallet.CalculateNetworkFee` is non-static.

**Comment by shargon** [comment]
Please, take a look to https://github.com/neo-project/neo/pull/1839
