### ISSUE TITLE
ApplicationLogs serialization

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo-modules#318]
**Modules**
ApplicationLogs and RPCClient Neo 3 preview 3

**Describe the bug**
ApplicationLogs Plugin serializes `Blockchain.ApplicationExecuted.Stack` as array of **StackItem** ([here](https://github.com/neo-project/neo-modules/blob/master/src/ApplicationLogs/LogReader.cs#L57)). RPCClient deserializes `RpcApplicationLog.Stack` as array of **ContractParameter** ([here](https://github.com/neo-project/neo-modules/blob/master/src/RpcClient/Models/RpcApplicationLog.cs#L42)). So there's a mismatch between serialization formats of application logs e.g. for ByteString stackitem type and ByteArray smartcontract parameter type.

**Expected behavior**
It would be great to unify serialization format for application logs.

**Comment by ProDog** [comment]
@AnnaShaleva please look https://github.com/neo-project/neo-modules/pull/321, now to serialize by `Utility.StackItemFromJson`.

**Comment by AnnaShaleva** [comment]
It's OK now, thank you for the response!
