### ISSUE TITLE
Add a Plugin for TPS test

### ISSUE THREAD

**Issue by Qiao-Jin** [neo-project/neo-modules#320]
**Summary or problem description**
Currently we don't have a commonly-used tool for TPS testing. People use varies kinds of tools / methods and it's very inconvenient.

**Do you have any solution you want to propose?**
Maybe we can add a plugin for the sake of TPS testing. This plugin should include functionalities as follows:

Constructing transactions needed beforehand
Send transactions in designated frequency
... etc

We can design this plugin on the basis of RPCPlugin for convenience.

**Where in the software does this update applies to?**
- Plugins

**Comment by erikzhang** [comment]
You can create such a plugin in your owner repository. `neo-modules` is only used to develop some important components, which are widely used. Otherwise, there will be more and more plugins in this repository, and it will become difficult to maintain.
