### ISSUE TITLE
RpcClient.GetApplicationLogs doesn't work w/ ApplicationLogs plugin

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#324]
The `notifications.state` array returned from `getapplicationlog` is a JSON serialized NeoVM array of stack items, but `RpcNotifyEventArgs.FromJson` is parsing it as a ContractParameter

**Comment by ProDog** [comment]
@devhawk It was fixed in https://github.com/neo-project/neo-modules/pull/321, please check it.

**Comment by devhawk** [comment]
Thanks for pointing that out @ProDog. Wish we had fixed this for preview 3. Closing this issue as a duplicate
