### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ryanfalzon** [neo-project/neo-modules#325]
Getting the error: System.NullReferenceException: 'Object reference not set to an instance of an object.'

Stacktrace:
   at Neo.Network.RPC.Models.RpcInvokeResult.FromJson(JObject json)
   at Neo.Network.RPC.RpcClient.InvokeScript(Byte[] script, UInt160[] scriptHashesForVerifying)

Code:
`
RpcClient client = new RpcClient("http://localhost:10332");
UInt160 scriptHash = NativeContract.NEO.Hash;
byte[] script = scriptHash.MakeScript("name");
var name = client.InvokeScript(script).Stack.Single().ToStackItem().GetString();
`

**Comment by ProDog** [comment]
It was fixed in https://github.com/neo-project/neo-modules/pull/303, maybe the code you are using has not been updated.
Now you can using it:  var name = rpcClient.InvokeScript(script).Stack.Single().GetString();

**Comment by ryanfalzon** [comment]
I currently have Neo.Network.RPC.RpcClient v3.0.0-preview2 installed. Is this correct?

**Comment by ProDog** [comment]
You should use v3.0.0-preview3.

**Comment by ryanfalzon** [comment]
That is not available 
![image](https://user-images.githubusercontent.com/30478175/90487030-2a2a7600-e13a-11ea-8d5f-0499c0e0eb56.png)

The project that is calling it is .net core 3.1. Could that be the issue?

**Comment by ProDog** [comment]
Nuget package of preview3 has not yet published, you can use source code.
https://github.com/neo-project/neo-modules/releases/tag/v3.0.0-preview3-00

**Comment by ryanfalzon** [comment]
Thank you! Will test and revert back to close the issue 👍

**Comment by ryanfalzon** [comment]
If anyone ends with the same error above, solution suggested by @ProDog works perfectly!

**Comment by ryanfalzon** [comment]
Hi @ProDog another quick question. if I have the following contract function: 

```
[DisplayName("addPost")]
public static bool AddPost(string hash, byte[] creator, string content, long timestamp)
```

Is this the correct way to create a script invoke such function?

`byte[] script = scriptHash.MakeScript("addPost", "0x", "0242c646a99dfe0fc0b86342e6cf793cc1a9fe3421d89f63a2710fe1b1d981899b".HexToBytes(), "This is the content of the post", 1234);`

**Comment by ProDog** [comment]
Yes.
