### ISSUE TITLE
Unhandled exception when using RocksDBStore plugin

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo-modules#330]
**Describe the bug**
I'm using Neo 3 preview3 release of neo-cli and trying to switch from LevelDBStore to RocksDBStore Plugin. I'm able to install RocksDBStore via neo-cli, but when I'm trying to re-run neo-cli with `"Storage": {"Engine": "RocksDBStore"},` configuration, I get the following error:
```
NEO-CLI v3.0.0-preview3  -  NEO v3.0.0-preview3-00  -  NEO-VM v3.0.0-preview3

neo> [12:50:38.524] System.IO.FileNotFoundException
Could not load file or assembly 'RocksDbSharp, Version=6.2.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at Neo.Plugins.Storage.Store..ctor(String path)
   at Neo.Plugins.Storage.RocksDBStore.GetStore()
   at Neo.NeoSystem..ctor(String storageEngine)
   at Neo.CLI.MainService.Start(String[] args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'RocksDbSharp, Version=6.2.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'RocksDbSharp, Version=6.2.2.0, Culture=neutral, PublicKeyToken=null'
   at Neo.Plugins.Storage.Store..ctor(String path)
   at Neo.Plugins.Storage.RocksDBStore.GetStore()
   at Neo.NeoSystem..ctor(String storageEngine)
   at Neo.CLI.MainService.Start(String[] args)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()


Aborted (core dumped)
```

The same thing happens when I'm trying to install RocksDBStore Plugin manually. This problem looks like #198.

I tried also to unzip RocksDBSharp.dll into Plugins folder from [nuget.org](https://www.nuget.org/packages/RocksDbSharp/6.2.2), but then it turns out that RocksDBNative.dll is also required and missing

**To Reproduce**
1. Download and unzip neo-cli v3.0.0-preview3 for linux-x64 from [releases](https://github.com/neo-project/neo-node/releases/tag/v3.0.0-preview3)
2. Download RocksDBStore Plugin v3.0.0-preview3 from [releases](https://github.com/neo-project/neo-modules/releases/tag/v3.0.0-preview3-00)
3. Unzip RocksDBStore plugin into neo-cli/Plugins/ folder as described in guide
4. Setup single-node environment as described in guide (with `"Storage": {"Engine": "RocksDBStore"},` configuration)
5. Run ./neo-cli

**Expected behavior**
Node is running with RocksDB storage.

**Platform:**
 - OS: Ubuntu 18.04.4 LTS (Bionic Beaver)
 - Version: neo-cli  v3.0.0-preview3

**Comment by shargon** [comment]
Could you check this change https://github.com/neo-project/neo-modules/pull/332 ?

**Comment by AnnaShaleva** [comment]
I built #332 and put binaries into `Plugins` folder. Unfortunately, this does not solve the problem.

**Comment by shargon** [comment]
I see that your error was different to my error, i will check it again

**Comment by kokahunter** [comment]
I experienced this with previous neo versions and leveldb. rocksdb.dll is probably missing in neo-cli path. 

This is small challenge as well when developing plugins with other dependencies as you have to find out which dll is needed in neo-cli path and which in the plugin path. 

Would be nice to have a cleaner solution for this.

**Comment by shargon** [comment]
The release binary doesn't contains the dependencies. Could you create a new relase with it @superboyiii ? Also it will require #332 for work.

**Comment by superboyiii** [comment]
> The release binary doesn't contains the dependencies. Could you create a new relase with it @superboyiii ? Also it will require #332 for work.

Fine, whenever it's merged.

**Comment by superboyiii** [comment]
> I experienced this with previous neo versions and leveldb. rocksdb.dll is probably missing in neo-cli path.
> 
> This is a small challenge as well when developing plugins with other dependencies as you have to find out which dll is needed in neo-cli path and which in the plugin path.
> 
> Would be nice to have a cleaner solution for this.

Are you in linux? Would you like to try install this dependency? https://github.com/neo-project/docs/pull/1127

**Comment by AnnaShaleva** [comment]
It works fine with `sudo apt-get install librocksdb-dev`. Thank you!
