### ISSUE TITLE
Update TransactionManager to support magic parameter

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#343]
**Summary or problem description**
https://github.com/neo-project/neo/pull/1902 added overload of `IVerifiable.Sign` that takes an explicit magic value. Transaction Manager needs to be updated to take an optional magic value parameter to its constructor (defaulting to Protocol.Default.Magic if not provided) that is in turn passed to `Tx.Sign` in `TransactionManager.Sign[Async]`

Should probably wait until after #335 is merged before doing this

**Where in the software does this update applies to?**
RPC

**Comment by superboyiii** [comment]
> **Summary or problem description**
> [neo-project/neo#1902](https://github.com/neo-project/neo/pull/1902) added overload of `IVerifiable.Sign` that takes an explicit magic value. Transaction Manager needs to be updated to take an optional magic value parameter to its constructor (defaulting to Protocol.Default.Magic if not provided) that is in turn passed to `Tx.Sign` in `TransactionManager.Sign[Async]`
> 
> Should probably wait until after #335 is merged before doing this
> 
> **Where in the software does this update applies to?**
> RPC

#335 is merged. Now we can do this.

**Comment by devhawk** [comment]
This was fixed as part of #335: https://github.com/neo-project/neo-modules/pull/335#issuecomment-693491796
