### ISSUE TITLE
Remove sender from invoke* RPCs

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo-modules#351]
**Summary or problem description**
neo-project/neo-modules#309 had introduced a `sender` parameter for `invokescript` and `invokefunction` RPCs, supposedly to solve the problem of `null` here:
```c#
tx = wallet.MakeTransaction(result["script"].AsString().HexToBytes(), null, witnessCosigners);
```

But it's not really needed as the sender is the first signer and `signers` are perfectly ordered to rely on this. At the moment having both an explicit `sender` and `signers` creates some duplication along with additional error modes that we need to check for. I don't see anything we couldn't do without an explicit `sender` (just with `signers`).

**Do you have any solution you want to propose?**
Something like this should solve the problem:
```c#
tx = wallet.MakeTransaction(result["script"].AsString().HexToBytes(), witnessSigners[0], witnessSigners);
```
And allow to simplify the RPC API (returning to the parameter set we had for preview3).

**Where in the software does this update applies to?**
- RPC (HTTP)

**Comment by ixje** [comment]
Agreed. https://github.com/neo-project/neo/pull/1752 fixed the sender to the first signer.

**Comment by Tommo-L** [comment]
I think it's clear enough.
https://github.com/neo-project/neo-modules/blob/fed3f7a87d65d91bbe4e42bce94734cc76571d5c/src/RpcServer/RpcServer.Wallet.cs#L168

**Comment by ixje** [comment]
I don't understand your comment? 

The discussion is about removing the mandatory `sender` param for the `invokescript` and `invokefunction` RPC calls when you want to add signers, because `signer[0]` is already always the sender.

https://github.com/neo-project/neo-modules/blob/fed3f7a87d65d91bbe4e42bce94734cc76571d5c/src/RpcServer/RpcServer.SmartContract.cs#L120-L121

**Comment by Tommo-L** [comment]
You are right, we should remove it. Plz see https://github.com/neo-project/neo-modules/pull/368

**Comment by superboyiii** [comment]
> **Summary or problem description**
> #309 had introduced a `sender` parameter for `invokescript` and `invokefunction` RPCs, supposedly to solve the problem of `null` here:
> 
> ```cs
> tx = wallet.MakeTransaction(result["script"].AsString().HexToBytes(), null, witnessCosigners);
> ```
> 
> But it's not really needed as the sender is the first signer and `signers` are perfectly ordered to rely on this. At the moment having both an explicit `sender` and `signers` creates some duplication along with additional error modes that we need to check for. I don't see anything we couldn't do without an explicit `sender` (just with `signers`).
> 
> **Do you have any solution you want to propose?**
> Something like this should solve the problem:
> 
> ```cs
> tx = wallet.MakeTransaction(result["script"].AsString().HexToBytes(), witnessSigners[0], witnessSigners);
> ```
> 
> And allow to simplify the RPC API (returning to the parameter set we had for preview3).
> 
> **Where in the software does this update applies to?**
> 
> * RPC (HTTP)

Why Signers[0] should be the sender? Signers[1], Signers[2] could also be sender, that's why we have to confirm the sender in params

**Comment by ixje** [comment]
No sender is fixed. See https://github.com/neo-project/neo-modules/issues/351#issuecomment-702741394

**Comment by superboyiii** [comment]
> No sender is fixed. See [#351 (comment)](https://github.com/neo-project/neo-modules/issues/351#issuecomment-702741394)
> […](#)
> Why Signers[0] should be the sender? Signers[1], Signers[2] could also be sender, that's why we have to confirm the sender in params — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for remind.

**Comment by superboyiii** [comment]
> > No sender is fixed. See [#351 (comment)](https://github.com/neo-project/neo-modules/issues/351#issuecomment-702741394)
> > […](#)
> > Why Signers[0] should be the sender? Signers[1], Signers[2] could also be sender, that's why we have to confirm the sender in params — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Thanks for remind.

**Comment by roman-khimov** [comment]
> You see in neo-cli, I could still make the second address as sender.

I doubt it's useful, you can use the same convention here and always the first signer as a sender.

> I think invokefunction in RPC should be the same mechanism.

But even if you find it useful, you can hide it completely in the client (`neo-cli` here) and use regular encoding scheme with `signers[0] == sender` for the RPC call. An explicit sender parameter for RPC call is just redundant data and the need to do additional error checking that could easily be avoided.

**Comment by superboyiii** [comment]
> > You see in neo-cli, I could still make the second address as sender.
> 
> I doubt it's useful, you can use the same convention here and always get the sender for the first signer.
> 
> > I think invokefunction in RPC should be the same mechanism.
> 
> But even if you find it useful, you can hide it completely in the client (`neo-cli` here) and use regular encoding scheme with `signers[0] == sender` for the RPC call. An explicit sender parameter for RPC call is just redundant data and the need to do additional error checking that could easily be avoided.

Please have a look at my test result.
https://github.com/neo-project/neo-modules/pull/368#issuecomment-706494014

I think the meaning of sender is to show who makes the transaction. And signer is who pays for the transaction. Like we buy something online, we could make this order and ask our friend or families to pay for it. if you'd like to make it as who paid it, then he is the sender, it's OK. But we must modify `MakeTransaction()` in `wallet.cs` to ensure sender not be checked for balance even if it has no asset.

**Comment by shargon** [comment]
sender is who pay the fee, signers is who sign that this transaction it's ok. because sender must be a signer, we decided to use the first entry for it.

**Comment by superboyiii** [comment]
> sender is who pay the fee, signers is who sign that this transaction it's ok. because sender must be a signer, we decided to use the first entry for it.

If designed like this ,then we should modify here, because what we input is not what we get. I use a non-asset address to be the signer, it doesn't return `insufficient balance` but automatically choose another address as signer which will make people confused.
![image](https://user-images.githubusercontent.com/38493437/95648155-a4a6bf00-0b07-11eb-86f2-58da97baea3e.png)
```
{
  "jsonrpc": "2.0",
  "method": "invokefunction",
  "params": [
    "0x254b9decd76080ef368e7a6b0a065938dfbc31cf",
    "balanceOf",
    [
      {
        "type": "Hash160",
        "value": "0xf642a0401fdd56a03114639a98b7963eb587a30a"
      }
    ],
    [
      {
        "account": "0xef9b39f97b13be48a48ee1bbdd4c9b35024778ca",
        "scopes": "CalledByEntry"
      }
    ]
  ],
  "id": 3
}
```

```
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "0c140aa387b53e96b7989a631431a056dd1f40a042f611c00c0962616c616e63654f660c14cf31bcdf3859060a6b7a8e36ef8060d7ec9d4b2541627d5b52",
        "state": "HALT",
        "gasconsumed": "3840690",
        "stack": [
            {
                "type": "Integer",
                "value": "2000000000000000"
            }
        ],
        "tx": "001e3fa04eb29a3a0000000000a4e2230000000000ea162000020aa387b53e96b7989a631431a056dd1f40a042f600ca784702359b4cddbbe18ea448be137bf9399bef01003e0c140aa387b53e96b7989a631431a056dd1f40a042f611c00c0962616c616e63654f660c14cf31bcdf3859060a6b7a8e36ef8060d7ec9d4b2541627d5b5202420c40f01f3b9890929d86af6ee3aa0bf8089e5097d9a9acc506067e546aa3ccbca61508122c44f8e6a4e92974e21fde3f92e5c60555b5b050e7fab5a63ce99cbe00bc290c2103cea3e2f81f1af93522d29ede4f24a1f0bedead7293391d33880f5475d97878c90b4195440d78420c40df98a383c5858f11826f7edb765881ddc9d8c0583aef9221368f88a56308c21250f0bb4dfacb5012b9bd87dd8270fadfc474b86d4dd5ec308d15c11c2c0c5429290c21029e86bfd7666b1e11105ed7f427758b4bcde8db6d5e7c8eb3aea1316abfcd6b3a0b4195440d78"
    }
}
```
```
{
  "jsonrpc": "2.0",
  "method": "sendrawtransaction",
  "params": ["001e3fa04eb29a3a0000000000a4e2230000000000ea162000020aa387b53e96b7989a631431a056dd1f40a042f600ca784702359b4cddbbe18ea448be137bf9399bef01003e0c140aa387b53e96b7989a631431a056dd1f40a042f611c00c0962616c616e63654f660c14cf31bcdf3859060a6b7a8e36ef8060d7ec9d4b2541627d5b5202420c40f01f3b9890929d86af6ee3aa0bf8089e5097d9a9acc506067e546aa3ccbca61508122c44f8e6a4e92974e21fde3f92e5c60555b5b050e7fab5a63ce99cbe00bc290c2103cea3e2f81f1af93522d29ede4f24a1f0bedead7293391d33880f5475d97878c90b4195440d78420c40df98a383c5858f11826f7edb765881ddc9d8c0583aef9221368f88a56308c21250f0bb4dfacb5012b9bd87dd8270fadfc474b86d4dd5ec308d15c11c2c0c5429290c21029e86bfd7666b1e11105ed7f427758b4bcde8db6d5e7c8eb3aea1316abfcd6b3a0b4195440d78"],
  "id": 1
}
```
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "hash": "0x7b3c8ae059ba7cd18d98cedcf8bb3c455ca4668921500274ea4e600be00bdc29"
    }
}
```

```
{
  "jsonrpc": "2.0",
  "method": "getrawtransaction",
  "params": ["0x7b3c8ae059ba7cd18d98cedcf8bb3c455ca4668921500274ea4e600be00bdc29", 1],
  "id": 1
}
```
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "hash": "0x7b3c8ae059ba7cd18d98cedcf8bb3c455ca4668921500274ea4e600be00bdc29",
        "size": 351,
        "version": 0,
        "nonce": 1319124766,
        "sender": "NLtDqwnj9s7wQVyaiD5ohjV3e9fUVkZxDp",
        "sysfee": "3840690",
        "netfee": "2351780",
        "validuntilblock": 2103018,
        "signers": [
            {
                ***"account": "0xf642a0401fdd56a03114639a98b7963eb587a30a",
                "scopes": "None"***
            },
            {
                "account": "0xef9b39f97b13be48a48ee1bbdd4c9b35024778ca",
                "scopes": "CalledByEntry"
            }
        ],
        "attributes": [],
        "script": "DBQKo4e1Ppa3mJpjFDGgVt0fQKBC9hHADAliYWxhbmNlT2YMFM8xvN84WQYKa3qONu+AYNfsnUslQWJ9W1I=",
        "witnesses": [
            {
                "invocation": "DEDwHzuYkJKdhq9u46oL+AieUJfZqazFBgZ+VGqjzLymFQgSLET45qTpKXTiH94/kuXGBVW1sFDn+rWmPOmcvgC8",
                "verification": "DCEDzqPi+B8a+TUi0p7eTySh8L7erXKTOR0ziA9Uddl4eMkLQZVEDXg="
            },
            {
                "invocation": "DEDfmKODxYWPEYJvftt2WIHdydjAWDrvkiE2j4ilYwjCElDwu036y1ASub2H3YJw+t/EdLhtTdXsMI0VwRwsDFQp",
                "verification": "DCECnoa/12ZrHhEQXtf0J3WLS83o221efI6zrqExar/NazoLQZVEDXg="
            }
        ],
        "blockhash": "0x79e4f4084102e63dcb39153114137312660a556689080596f6a931ed04ab45c6",
        "confirmations": 3,
        "blocktime": 1602312595703,
        "vmstate": "HALT"
    }
}
```

**Comment by roman-khimov** [comment]
> I use a non-asset address to be the signer, it doesn't return insufficient balance but automatically choose another address as signer which will make people confused.

I guess the server just shouldn't do that. In you example you only specify one signer for `invokefunction`:
```
    [
      {
        "account": "0xef9b39f97b13be48a48ee1bbdd4c9b35024778ca",
        "scopes": "CalledByEntry"
      }
    ]
```
Which to me means that he also is a sender, so the fact that you get this in returned transaction:
```
        "signers": [
            {
                "account": "0xf642a0401fdd56a03114639a98b7963eb587a30a",
                "scopes": "None"
            },
            {
                "account": "0xef9b39f97b13be48a48ee1bbdd4c9b35024778ca",
                "scopes": "CalledByEntry"
            }
        ],
```
is a bug to me. Instead it should be:
```
        "signers": [
            {
                "account": "0xef9b39f97b13be48a48ee1bbdd4c9b35024778ca",
                "scopes": "CalledByEntry"
            }
        ],
```
Or no transaction returned at all as it's not possible to create a valid transaction for a given sender.

This logic for automatically choosing the sender is actually a bit dangerous and can lead to unexpected results when you have multiple mixed zero-balance and non-zero-balance accounts in a wallet.

**Comment by superboyiii** [comment]
> > I use a non-asset address to be the signer, it doesn't return insufficient balance but automatically choose another address as signer which will make people confused.
> 
> I guess the server just shouldn't do that. In you example you only specify one signer for `invokefunction`:
> 
> ```
>     [
>       {
>         "account": "0xef9b39f97b13be48a48ee1bbdd4c9b35024778ca",
>         "scopes": "CalledByEntry"
>       }
>     ]
> ```
> 
> Which to me means that he also is a sender, so the fact that you get this in returned transaction:
> 
> ```
>         "signers": [
>             {
>                 "account": "0xf642a0401fdd56a03114639a98b7963eb587a30a",
>                 "scopes": "None"
>             },
>             {
>                 "account": "0xef9b39f97b13be48a48ee1bbdd4c9b35024778ca",
>                 "scopes": "CalledByEntry"
>             }
>         ],
> ```
> 
> is a bug to me. Instead it should be:
> 
> ```
>         "signers": [
>             {
>                 "account": "0xef9b39f97b13be48a48ee1bbdd4c9b35024778ca",
>                 "scopes": "CalledByEntry"
>             }
>         ],
> ```
> 
> Or no transaction returned at all as it's not possible to create a valid transaction for a given sender.
> 
> This logic for automatically choosing the sender is actually a bit dangerous and can lead to unexpected results when you have multiple mixed zero-balance and non-zero-balance accounts in a wallet.

Yes, that's the point. We should return `insufficient balance` in `MakeTransaction` instead of automatically choosing the sender. If modified like this, https://github.com/neo-project/neo-modules/pull/368 makes sense.
