### ISSUE TITLE
`OnPersist` and `PostPersist` have the same application log hash

### ISSUE THREAD

**Issue by fyrchik** [neo-project/neo-modules#354]
**Describe the bug**
After addition of `postPersist` method, we have 2 scripts with their own application logs (`onPersist` and `postPersist`), which are both saved and queried by the block hash.
https://github.com/neo-project/neo-modules/blob/master/src/ApplicationLogs/LogReader.cs#L78

**Expected behavior**
Both `onPersist` and `postPersist` scripts should be accessible for query by `getapplicationlog` RPC.

**Comment by roman-khimov** [comment]
IMO the situation is a little worse than just an RPC problem, because it's impossible to differentiate between these two `ApplicationExecuted` events generated by the system, so all users of this event stream might be affected.

**Comment by Tommo-L** [comment]
I think it's reasonable, `onPersist` and `postPersist`, which are both saved and queried by the block hash.

**Comment by roman-khimov** [comment]
So, how do we store both with the same key and which one do we return when there is a `getapplicationlog` request for block hash?

**Comment by Tommo-L** [comment]
I got your point, they both use the same storage key.

**Comment by erikzhang** [comment]
I prefer to use different triggers.

**Comment by shargon** [comment]
Does we need to publish the result `Context.System.EventStream.Publish(application_executed);` ?

**Comment by roman-khimov** [comment]
Absolutely. Events are important and events can be generated in any execution context, be it block or transaction. And they're generated already for blocks (GAS burn/mint events).

**Comment by Tommo-L** [comment]
> I prefer to use different triggers.

Any more details about "different triggers"?

**Comment by superboyiii** [comment]
@erikzhang Any solution? Or shall we move it to the version after preview4?

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo/blob/6fc4161258408cae3d754cab784dcee2235b63ef/src/neo/SmartContract/TriggerType.cs#L5-L27

We can use different triggers to call these two methods.

**Comment by roman-khimov** [comment]
I don't think we can close this one. neo-project/neo#2022 makes it possible to solve this, but we still need to decide how to store and request these.

**Comment by Tommo-L** [comment]
https://github.com/neo-project/neo-modules/pull/380 fixed?

**Comment by roman-khimov** [comment]
Not yet, it solves storage problem, but `getapplicationlog` needs to be updated to take this change into account. The way #380 is now actually breaks the plugin completely, `GetApplicationLog` still does `db.Get(ReadOptions.Default, hash.ToArray())` and now the key has changed.

We'll probably need another parameter for `getapplicationlog` (trigger) and then decide on behavior for requests lacking this parameter (for transactions that's easy, but for blocks I'd probably answer with an array of execution results for different triggers).

**Comment by Tommo-L** [comment]
Close? I think it was fixed by #380

**Comment by roman-khimov** [comment]
Yep, I think we're fine now. We've implemented the same scheme in neo-go and it works.
