### ISSUE TITLE
Expand getversion RPC call output with network's magic number

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo-modules#358]
**Summary or problem description**
As all hashes and signatures are network-dependent now all clients need to know the magic number of the network. This magic number can be configured explicitly in the client, but I think we can do a bit better than that by making it discoverable from the server.

**Do you have any solution you want to propose?**
I don't think it's worth another RPC call, we can just add a `magic` field to the `getversion` RPC call return value.

In general, this follows the same line as #355 (and maybe intersects a bit with intentions of neo-project/neo#1977), I'd really like the client to have exactly one thing to configure --- RPC endpoint to use, everything else it needs should be available from that.

**Where in the software does this update applies to?**
- RPC (HTTP)

**Comment by realloc** [comment]
This feature is needed for NeoFS to work with sidechain. Sharing or hardcoding common privnet magic number may be a security issue.

**Comment by shargon** [comment]
Agree
