### ISSUE TITLE
REQ: RPC call to request unclaimedGas for light wallets

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-modules#360]
**Summary or problem description**
Light wallets like [neon-wallet](https://github.com/CityOfZion/neon-wallet) often show the user how much unclaimed gas they can claim. In NEO2 for years such light wallets depended on external full node information providers for this information (e.g. neoscan). For NEO3 there now is the `getwalletunclaimedgas` RPC call, but that is limited to wallets opened by the node and is thus not useful for light wallets. 

The current way to obtain the necessary information is by using the `invokefunction` RPC call. This is very user **un**friendly because it first requires an RPC call to `getblockcount` in order to be able to get the end height for the bonus calculation, and then possibly requires multiple calls if a wallet has multiple addresses. 

**Do you have any solution you want to propose?**
I'd like to propose a `getunclaimedgas` RPC call that does not require an open wallet on the node that is providing the RPC service. It takes a list of addresses and returns the claimable gas per address. The implementation can automatically insert the height of the blockchain, avoiding the need for the user to do the `getblockcount` RPC call before calling `getunclaimedgas`. 

The existing `getwalletunclaimedgas` call could even be refactored to internally call the `getunclaimedgas` implementation for all accounts in the open wallet.

**Where in the software does this update applies to?**
- RPC (HTTP)

**Comment by roman-khimov** [comment]
Isn't it solved by #241/#243?

**Comment by ixje** [comment]
Wow I completely missed that. Probably because it isn't in the documentation.
