### ISSUE TITLE
InvokeScript RpcClient sending Base64 but RpcServer expecting Hex

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#385]
**Describe the bug**
Script format mismatch between RpcClient and RpcServer

I believe this is a **MUST FIX** for [preview 4](https://github.com/neo-project/neo/issues/1936)

[RpcClient](https://github.com/neo-project/neo-modules/blob/9729f7e36ef544f1da967f28f7df71d93925f860/src/RpcClient/RpcClient.cs#L376-L385) passes script parameter as string after calling `Convert.ToBase64String(script)`

``` csharp
public async Task<RpcInvokeResult> InvokeScriptAsync(byte[] script, params Signer[] signers)
{
    List<JObject> parameters = new List<JObject> { Convert.ToBase64String(script) };
    if (signers.Length > 0)
    {
        parameters.Add(signers.Select(p => p.ToJson()).ToArray());
    }
    var result = await RpcSendAsync(GetRpcName(), parameters.ToArray()).ConfigureAwait(false);
    return RpcInvokeResult.FromJson(result);
}
``` 

[RpcServer](https://github.com/neo-project/neo-modules/blob/9729f7e36ef544f1da967f28f7df71d93925f860/src/RpcServer/RpcServer.SmartContract.cs#L120-L126) attempts to parse the script parameter via HexToBytes

``` csharp
[RpcMethod]
protected virtual JObject InvokeScript(JArray _params)
{
    byte[] script = _params[0].AsString().HexToBytes();
    Signers signers = _params.Count >= 2 ? SignersFromJson((JArray)_params[1]) : null;
    return GetInvokeResult(script, signers);
}
```

**Comment by roman-khimov** [comment]
RpcServer was converted to using base64 in #362, but then it looks like the old code was partially reintroduced with #368. What's really weird is that this wasn't caught by any unit test.

**Comment by devhawk** [comment]
I confirmed that changing the first line of `RpcServer` `InvokeScript` to `byte[] script = Convert.FromBase64String(_params[0].AsString());` solves the issue

**Comment by superboyiii** [comment]
> I confirmed that changing the first line of `RpcServer` `InvokeScript` to `byte[] script = Convert.FromBase64String(_params[0].AsString());` solves the issue

Fixed: https://github.com/neo-project/neo-modules/pull/386
