### ISSUE TITLE
[RpcClient] Transfer return Invalid with RpcClient

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-modules#387]
**Describe the bug**

When I use `RpcClient` to transfer asset, it will fail and return `Invalid`, it looks like the RpcClient make transaction  is wrong.

The method I test it is this:
https://github.com/neo-project/neo-modules/blob/f88961d0c1348b1d5f01fc0c2a1ae25532c83f59/src/RpcClient/WalletAPI.cs#L135

My transaction is:
```
00c0654d0598808c00000000009e7f1400000000000c1a2000011c0357464b777ecf6b5f3ac3893ace1f8b1621f6010054140c14995dca495a0a902b7512254299972abb6df5011e0c141c0357464b777ecf6b5f3ac3893ace1f8b1621f613c00c087472616e736665720c1425059ecb4878d3a875f91c51ceded330d4575fde41627d5b5201420c40f82c9b6c33c3a402c0c2496dd4f70b29f634f0f34d092671d0f79e9d1998e03e3c0837a31ad52e41068430b38dca3edc9b662b07ff0d0d0346102c0aec56bc16290c210222d8515184c7d62ffa99b829aeb4938c4704ecb0dd7e340e842e9df1218263430b4195440d78
```
I traced it will returns `false` at here:

![image](https://user-images.githubusercontent.com/12728872/98322357-2b28c080-2022-11eb-9d81-4912844d1b95.png)

**Platform:**
 - OS: [Windows 10 x64]
 - Version [neo master last version]

**Comment by chenzhitong** [comment]
I found that the transaction constructed by RpcClient is different from the one constructed on Neo-CLI.

**Comment by ProDog** [comment]
Now tests are normal and don't reproduce it, so close it.
