### ISSUE TITLE
Neo3: unify encoding for bytes-related RPC requests

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo-modules#392]
**Summary or problem description**
https://github.com/neo-project/neo-modules/pull/383 and https://github.com/neo-project/neo-modules/pull/384 unified `getblock`, `getblockheader` and `getrawtransaction` responses to base64 encoding. It would be really nice to change the input encoding from hex to base64 for:
* `submitblock`
* `sendrawtransaction`

Ther's also `ProcessInvokeWithWallet` method which returns hex-encoded transaction bytes and needs to be unified too.

**Do you have any solution you want to propose?**
Change block- and transaction- related bytes encoding from hex to base64 for `submitblock`, `sendrawtransaction` and `ProcessInvokeWithWallet`.

**Where in the software does this update applies to?**
- RPC (HTTP)

**Comment by Tommo-L** [comment]
Fixed #394
