### ISSUE TITLE
RPCServer: `invoke*` RPC requests failures

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo-modules#398]
**Describe the bug**
https://github.com/neo-project/neo-modules/pull/390 broke `invokefunction` and `invokescript` RPC requests handlers. In the case of missing signers, the response to these requests is the following:
```
{
   "jsonrpc" : "2.0",
   "id" : 1,
   "error" : {
      "message" : "Object reference not set to an instance of an object.",
      "code" : -2147467261
   }
}
```

The reason is that the default value for `signers` is `null` ([here](https://github.com/neo-project/neo-modules/blob/master/src/RpcServer/RpcServer.SmartContract.cs#L116), [here](https://github.com/neo-project/neo-modules/blob/master/src/RpcServer/RpcServer.SmartContract.cs#L130) and [here](https://github.com/neo-project/neo-modules/blob/master/src/RpcServer/RpcServer.SmartContract.cs#L64)) which results in `NullReferenceException` right [here](https://github.com/neo-project/neo-modules/blob/master/src/RpcServer/RpcServer.SmartContract.cs#L68).

**To Reproduce**
Steps to reproduce the behaviour:
1. Send the following RPC request to the Neo node with RPCServer plugin installed from the current [master](https://github.com/neo-project/neo-modules/commit/f43c5abfeafae49d8ed84f4112a8f3fdd0c69c10):
```
curl -d '{ "jsonrpc": "2.0", "id": 1, "method": "invokefunction", "params": ["0x668e0c1f9d7b70a99dd9e06eadd4c784d641afbc", "name"]}' localhost:20331 | json_pp
```
2. The result response is the following:
```
{
   "jsonrpc" : "2.0",
   "id" : 1,
   "error" : {
      "message" : "Object reference not set to an instance of an object.",
      "code" : -2147467261
   }
}
```
**Expected behaviour**
Request should be correctly processed and GAS native contract name should be returned:
```
{
   "result" : {
      "stack" : [
         {
            "value" : "R0FT",
            "type" : "ByteString"
         }
      ],
      "gasconsumed" : "1007570",
      "state" : "HALT",
      "script" : "EMAMBG5hbWUMFLyvQdaEx9StbuDZnalwe50fDI5mQWJ9W1I=",
      "exception" : null
   },
   "jsonrpc" : "2.0",
   "id" : 1
}
```

**Additional context**
So it would be nice to set the default `signers` value to an empty array in case if params count < 4 for `invokefunction` and `invokescript` RPC handlers.

**Comment by devhawk** [comment]
I just ran into the same behavior

**Comment by superboyiii** [comment]
> I just ran into the same behavior
> 
> I'm not using curl, but I was able to make invoke script work in C# by including a dummy signer.
> 
> ```cs
> var signer = new Signer() { Account = UInt160.Zero };
> var invokeResult = await rpcClient.InvokeScriptAsync(script, signer).ConfigureAwait(false);
> ```
> 
> @AnnaShaleva, I think if you added the following json to the param array, it would work:
> 
> ```json
> {[{"account":"0x0000000000000000000000000000000000000000","scopes":"None"}]}
> ```

Yes, @AnnaShaleva  Currently, you could make any scopes to be added when no signers-needed method are invoked.

**Comment by AnnaShaleva** [comment]
@devhawk, @superboyiii thank you for the response! Still, it would be nice to support `invoke*` RPC calls without signers.
