### ISSUE TITLE
StateService project doesn't compile

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#415]
I'm guessing there should be a reference to neo.dll package?

```
MPT\MPTNodeType.cs(7,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
MPT\MPTNodeType.cs(9,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
MPT\MPTNodeType.cs(11,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
MPT\MPTNodeType.cs(13,10): error CS0404: Cannot apply attribute class 'ReflectionCache<T>' because it is generic [C:\Users\harry\Source\neo\official\modules\src\StateService\StateService.csproj]
```

**Comment by devhawk** [comment]
Note, ReflectionCacheAttribute is internal, so it can't be accessed from StateService project

**Comment by cloud8little** [comment]
https://github.com/neo-project/neo-modules/pull/414 should solve this. @devhawk

**Comment by cloud8little** [comment]
https://github.com/neo-project/neo/pull/2109

**Comment by devhawk** [comment]
@cloud8little I don't think https://github.com/neo-project/neo/pull/2109 will solve this issue.

**Comment by cloud8little** [comment]
> @cloud8little I don't think [neo-project/neo#2109](https://github.com/neo-project/neo/pull/2109) will solve this issue.

try this: https://github.com/neo-project/neo-modules/pull/414/

**Comment by devhawk** [comment]
> > @cloud8little I don't think [neo-project/neo#2109](https://github.com/neo-project/neo/pull/2109) will solve this issue.
> 
> try this: #414

I'll test it out after it gets merged

**Comment by bettybao1209** [comment]
close?
