### ISSUE TITLE
NeoFS integration

### ISSUE THREAD

**Issue by ZhangTao1596** [neo-project/neo-modules#417]
## Introduction
This is a issue to share neofs integration schedule

## Details
Here are the tasks in progress

* **neofs-node** 
this is a plugin contains `neofs-innerring` and `neofs-storage`, code: [innerring-node](https://github.com/neo-ngd/neo-plugins/tree/neofs-ir), [storage-node](https://github.com/neo-ngd/neo-plugins/tree/neofs-storage), https://github.com/neo-ngd/neo-plugins/pull/3

* **neofs-api-csharp**
 c# implement [neofs-api](https://github.com/nspcc-dev/neofs-api), code: https://github.com/neo-ngd/neofs-api-csharp/tree/jindo

* **neofs-cli**
this is a plugin to enable neo-cli to communicate with `neofs`, will build after `neofs-api-csharp` ready.

Currently they are still under developing, not all code exists in [neo-ngd](https://github.com/neo-ngd/neo-plugins). We build and test in [neo-ngd](https://github.com/neo-ngd) and commit pr to this repo when they are ready.

**Comment by roman-khimov** [comment]
I think the most important thing here is to get **neofs-api-csharp** to the point where it could allow porting nspcc-dev/neo-go#1484 (specifically the last commit from it, this PR needs a rebase now because Oracle module has changed). We'll have NeoFS available to smart contracts then and could run the network, so people could also write contracts and test it.

**Comment by ZhangTao1596** [comment]
> I think the most important thing here is to get **neofs-api-csharp** to the point where it could allow porting [nspcc-dev/neo-go#1484](https://github.com/nspcc-dev/neo-go/pull/1484) (specifically the last commit from it, this PR needs a rebase now because Oracle module has changed). We'll have NeoFS available to smart contracts then and could run the network, so people could also write contracts and test it.

I'm testing `neofs-api-csharp`. Once all api are compatible with go implementation, I will release.

**Comment by eaba** [comment]
> 
> 
> > I think the most important thing here is to get **neofs-api-csharp** to the point where it could allow porting [nspcc-dev/neo-go#1484](https://github.com/nspcc-dev/neo-go/pull/1484) (specifically the last commit from it, this PR needs a rebase now because Oracle module has changed). We'll have NeoFS available to smart contracts then and could run the network, so people could also write contracts and test it.
> 
> I'm testing `neofs-api-csharp`. Once all api are compatible with go implementation, I will release.

@ZhangTao1596 any update on this

**Comment by eaba** [comment]
@ZhangTao1596 Thanks for your response. Given all you listed above, how would I go about setting up neofs local development for c#?
