### ISSUE TITLE
Preview4 GetNextBlockValidators returning empty

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#433]
**Describe the bug**
result of RPC call `GetNextBlockValidators` is `[]` with test on NeoCompiler Eco V3 network

**Comment by cloud8little** [comment]
It is because in https://github.com/neo-project/neo-modules/pull/338 getvalidators API was renamed to getnextblockvalidators, but the meaning of the API was unchanged.

**Comment by vncoelho** [comment]
Hi @cloud8little, I did not understand.
I got that it was renamed. 
It looks like we still need to fix its call, right?

**Comment by cloud8little** [comment]
> Hi @cloud8little, I did not understand.
> I got that it was renamed.
> It looks like we still need to fix its call, right?

yes, we should fix it. @Tommo-L

**Comment by chenzhitong** [comment]
Ready to fix, blocked by https://github.com/neo-project/neo-modules/issues/440
