### ISSUE TITLE
Add CI to test build of each module

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#437]
Add a command in the workflow to automatically check the build of each module.

`dotnet publish /src/$PLUGIN_TO_INCLUDE/$PLUGIN_TO_INCLUDE.csproj -c Release -o /src/$PLUGIN_TO_INCLUDE/app`

**Comment by chenzhitong** [comment]
![image](https://user-images.githubusercontent.com/6295602/102965592-19936d80-4529-11eb-8a28-cdfab41dcd4a.png)
