### ISSUE TITLE
All rpcserver are not working

### ISSUE THREAD

**Issue by chenzhitong** [neo-project/neo-modules#440]
**Describe the bug**
All rpcserver are not working，neo-node and neo-moduels is master branch.

**To Reproduce**
F5 neo-node
Send RPC request in postman

**Expected behavior**
No crash

**Screenshots**
![image](https://user-images.githubusercontent.com/6295602/102957197-d3ccaa00-4514-11eb-90bd-d3e543469116.png)

![image](https://user-images.githubusercontent.com/6295602/102956957-2bb6e100-4514-11eb-9460-561d51aa60ab.png)

**Platform:**
 - OS: Windows 10 x64
 - neo-node CI00243
 - neo-modules CI00198
 - neo CI01123

**Comment by erikzhang** [comment]
It seems that it's the issue in `Microsoft.AspNetCore.ResponseCompression`.

**Comment by superboyiii** [comment]
> It seems that it's the issue in `Microsoft.AspNetCore.ResponseCompression`.

Seems current `Microsoft.AspNetCore.ResponseCompression` doesn't support .Net 5.0. The latest one is 2.2.0 and has never been updated for two years.
![image](https://user-images.githubusercontent.com/38493437/103064905-23cc6f00-45f0-11eb-9348-ff89661b055d.png)
![image](https://user-images.githubusercontent.com/38493437/103065001-6130fc80-45f0-11eb-963f-089b22006b94.png)

**Comment by chenzhitong** [comment]
@superboyiii `Microsoft.AspNetCore.ResponseCompression` has an update, but it still doesn't work after the update.
![image](https://user-images.githubusercontent.com/6295602/103067326-9855dc80-45f5-11eb-9e19-1f7c62faf0be.png)

**Comment by superboyiii** [comment]
If we choose downgrade, we can apply https://github.com/neo-project/neo/pull/2178. But if we'd like to upgrade to .net5.0, we should apply https://github.com/neo-project/neo/pull/2179
