### ISSUE TITLE
RPCServer call to list native contract

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#460]
**Summary or problem description**
native contract are now a core feature of Neo Blockchain.
There should be an RPC call to list them, light wallets will easily query them in order to perform simply asset transfer, voting, among others.
It makes sense that they are not hard coded and we have an easy way to query them.

**Do you have any solution you want to propose?**
Add this call to RPCServer Smart Contract.

**Comment by chenzhitong** [comment]
OK
