### ISSUE TITLE
"Method not found" when calling APIs via REST 

### ISSUE THREAD

**Issue by newnya** [neo-project/neo-modules#468]
`{"jsonrpc":"2.0","id":"1","method":"getnewaddress","params":[]}`

I get this response

`[[jsonrpc] => 2.0, [id] => 1, [error] => [[code] => -32601, [message] => Method not found]]`

What's wrong in my request?

**Comment by newnya** [comment]
My node:
`NEO-CLI Version: 2.12.2.0`

**Comment by bettybao1209** [comment]
> ```
>     "RPC": {
>       "BindAddress": "127.0.0.1",
>       "Port": 10332,
>       "SslCert": "",
>       "SslCertPassword": ""
>     },
> ```

Did you install the plugin `RpcServer`?

**Comment by ProDog** [comment]
Before you can invoke this method you must：
* Open the wallet in NEO-CLI.
* Install the plugin `RpcWallet`.

**Comment by newnya** [comment]
@ProDog @bettybao1209 
```
NEO-CLI Version: 2.12.2.0

install RpcServer
Downloading from https://github.com/neo-project/neo-plugins/releases/download/v2.12.2/RpcServer.zip
error
install RpcWallet
Downloading from https://github.com/neo-project/neo-plugins/releases/download/v2.12.2/RpcWallet.zip
Plugin already exist.
```
I already had RpcWallet, and RpcServer does not exist.

**Comment by ProDog** [comment]
You need to restart the neo-cli after install plugin.

**Comment by newnya** [comment]
> 
> 
> You need to restart the neo-cli after install plugin.

It was already installed yesterday, then i closed the wallet, and now i opened it again and retried the API. Same result

**Comment by newnya** [comment]
Full request 
```

POST / HTTP/1.1
Host: 127.0.0.1:10332
Accept: */*
Connection: close
Accept-encoding: gzip, deflate
Content-type: application/json
User-agent: EHttpClient
Authorization: Basic dXNlcjpwYXNzd29yZA==
Content-Length: 63

{"jsonrpc":"2.0","id":"1","method":"getnewaddress","params":[]}
```

**Comment by ProDog** [comment]
1. Check the RpcWallet plugins in the Plugins directory
2. Start neo-cli with rpc: `dotnet neo-cli.dll -r`
3. Open wallet
4. `getnewaddress`

It is all right for me.

![image](https://user-images.githubusercontent.com/12728872/104870862-852ff580-5984-11eb-83e2-6a45894e3d6d.png)

![image](https://user-images.githubusercontent.com/12728872/104870889-97119880-5984-11eb-98e9-795626847686.png)

**Comment by newnya** [comment]
@ProDog Now it works. The only difference with you was that i was launching the wallet from a different folder than the one containing the executables , dll and config.

Before launching , i did
```
cd <another folder>
dotnet <neo-cli folder>\neo-cli.dll -r
```

Very strange.
Anyway now it works, thanks!
