### ISSUE TITLE
RpcServerSettings should use new BigDecimal decimal constructor instead of Parse

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#472]
converting `decimal` to `BigDecimal` by converting to string and then parsing is inefficient and subject to globalization errors like #466. The RpcServerSettings ctor should use the new decimal constructor (https://github.com/neo-project/neo/pull/2246) once it's available

**Comment by chenzhitong** [comment]
```c#
string input = "1,234.01";
var a = (long)BigDecimal.Parse(input, NativeContract.GAS.Decimals).Value;
var b = new BigDecimal(Convert.ToDecimal(input));
```
It seems that we can't use `new BigDecimal` instead of `BigDecimal.Parse`
because the two values are not equal.

You see, whether this PR https://github.com/neo-project/neo/pull/2248 can be used?

**Comment by devhawk** [comment]
@chenzhitong I'm suggesting that we don't use `BigDecimal.Parse` to convert `maxGasInvoke` and `maxFee` decimal values to BigDecimal in this code: https://github.com/neo-project/neo-modules/blob/fd52f21e4d7d91347386088e37faa348410c64a1/src/RpcServer/RpcServerSettings.cs#L51-L52
