### ISSUE TITLE
Invokefunction RPC will not get incomplete signature context in json response

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-modules#486]
Invokefunction RPC will not get incomplete signature context in json response as well as invokescript. Maybe we should also add `sign` method in RPC and then we could relay complete-signature tx via `sendrawtransaction`.

@shargon

**Comment by shargon** [comment]
Could you give me more details to the issue?

I think that the process should be:
- (RPC) Create desired transaction
- (No-RPC) Sign 
- (RPC) Send transaction and signature

**Comment by superboyiii** [comment]
> Could you give me more details to the issue?
> 
> I think that the process should be:
> 
> * (RPC) Create desired transaction
> * (No-RPC) Sign
> * (RPC) Send transaction and signature

Correct.
I mean here: https://github.com/neo-project/neo-modules/blob/34b068e9c489a80fddc6b363cec6adb2896d98fe/src/RpcServer/RpcServer.Wallet.cs#L193
For test purpose, I simply print it in Console on my local. But if we'd like to sign the incompleted signature, we should set it to Json response.
![image](https://user-images.githubusercontent.com/38493437/106080157-8239bf80-6151-11eb-9d7c-af59f289c8f6.png)

**Comment by shargon** [comment]
Please take a look to https://github.com/neo-project/neo-modules/pull/490
