### ISSUE TITLE
Using the exit command after installing the Oracle plugin causes the cli to become unresponsive

### ISSUE THREAD

**Issue by ProDog** [neo-project/neo-modules#494]
**Describe the bug**
Using the `exit` command after installing the `OracleService` plugin causes the neo-cli to become unresponsive.

**To Reproduce**
1. install `OracleService` plugin;
2. start neo-cli;
3. execute the `exit` command.

**Expected behavior**
Exit cli correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/12728872/106354290-b4067e00-632b-11eb-933b-73ac2142fb60.png)

**Platform:**
 - OS: [All]
 - Version [The latest master]

**Comment by shargon** [comment]
It's work for me, do you have anything else?

**Comment by ProDog** [comment]
No, I just add `OracleService` plugin and it will appear. Removing the `OracleService` plugin and it will work.

**Comment by ProDog** [comment]
Here into the loop and caused the bug.
https://github.com/neo-project/neo-modules/blob/3f99dadc7f05b084794f05001c3fa3808068dda1/src/OracleService/OracleService.cs#L63-L70

https://github.com/neo-project/neo-modules/blob/3f99dadc7f05b084794f05001c3fa3808068dda1/src/OracleService/OracleService.cs#L99-L107

**Comment by erikzhang** [comment]
https://github.com/neo-project/neo-modules/blob/3f99dadc7f05b084794f05001c3fa3808068dda1/src/OracleService/OracleService.cs#L171-L192

This method needs to use `CancellationToken`.

**Comment by chenzhitong** [comment]
Is this okay?
```c#
private void OnStop()
{
    cancelSource.Cancel();
    stopped = true; // add this line
    if (timer != null)
    {
        timer.Dispose();
        timer = null;
    }
}
```

**Comment by shargon** [comment]
@chenzhitong At the end of the method it should be ok
