### ISSUE TITLE
Make RocksDb plugin usable from Neo Express / Debugger

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#497]
With a few changes, neo express and debugger could use the RocksDb storage plugin directly rather than having a separate implementation.

* Must be able to create Store instance w/o using `IStorageProvider.GetStore` method. Easiest way to do that would be to make the Store class public
* Must be able to access `RocksDb.Checkpoint` method. Easiest way to do that would be to add a Checkpoint method to Store class 
* Provide mechanism to open a RocksDB instance for readonly
* Switch to [curiosity-ai fork of RocksDbSharp](https://www.nuget.org/packages/RocksDB/) which is [kept up to date](https://github.com/curiosity-ai/rocksdb-sharp) better than the original version
  * This switch is not required for use from Blockchain Toolkit, but it is the rocksdb package the Neo 3 previews of Blockchain Toolkit are using

Note, as part of this work, probably better NOT to use generic term "Store" for the IStore implementation in the RocksdDb plugin

**Comment by erikzhang** [comment]
`RocksDbStore` is just a simple wrapper of `RocksDb`. If you want to use it, why not use `RocksDb` directly?
