### ISSUE TITLE
StatesDumper should exclude Ledger contract

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo-modules#520]
**Summary or problem description**
As was discussed in neo-project/neo#2215 `Ledger` contract state can differ from node to node for at least two reasons:
 * different witness signatures
 * tail cutting (`MaxTraceableBlocks`)

For this reasons it's excluded from MPT and state root calculations in the `StateService`. And for the same reasons it should be excluded from `StatesDumper` output. This plugin is mostly useful for comparing state changes between different nodes and as `Ledger` state can't reliably be compared there is little value in dumping it.

**Do you have any solution you want to propose?**
Exclude `Ledger` contract state from `StatesDumper` plugin.

**Where in the software does this update applies to?**
- Plugins

**Comment by vncoelho** [comment]
@roman-khimov, I think that it can be disabled as default, but still optional since it should be able to dump all state changes.
