### ISSUE TITLE
AutoStart to OracleService plugin

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-modules#523]
**Summary description**

For operations and also to turn the OracleService a bit easier to test (integration tests), it would be good to start it automatically upon CLI start.

**Do you have any solution you want to propose?**

I think that a flag `AutoStart` could be added to the `config.json` of the OracleService, exactly like we have in the `DBFTPlugin`: https://github.com/neo-project/neo-modules/blob/master/src/DBFTPlugin/DBFTPlugin/config.json

**Where in the software does this update applies to?**
- Plugins: more specifically to the `OracleService` plugin.

**Comment by gsmachado** [comment]
Thinking a bit better, the same should be applied to other plugins, like `StateService`, `StateDumper`, etc etc.

**Comment by shargon** [comment]
StateDumper has no Start method. But agree with `Oracle` and `StateService`

**Comment by gsmachado** [comment]
@shargon check it out:

This is my `OracleService/config.json`:

```json
{
  "PluginConfiguration": {
    "Network": 5195086,
    "Nodes": [ ],
    "MaxTaskTimeout": 432000000,
    "AllowPrivateHost": true,
    "AllowedContentTypes": [ "application/json" ],
    "Https": {
      "Timeout": 15000
    },
    "NeoFS": {
      "EndPoint": "127.0.0.1:8080",
      "Timeout": 15000
    },
    "AutoStart": true
  }
}
```

Once the neo-node starts, this happens:

![image](https://user-images.githubusercontent.com/2124276/111197169-6cc40c00-85be-11eb-8619-8fa0d350cb9f.png)

If I start by the neo-node CLI, it's fine -- it starts.

If I add `"http://localhost:40332"` or `"localhost:40332"` or whatever to the `Nodes` attribute, it doesn't start either. Same behavior.

Is there anything I'm doing wrong here? Please, give me some light. ⚡  😄

**Comment by superboyiii** [comment]
> @shargon check it out:
> 
> This is my `OracleService/config.json`:
> 
> ```json
> {
>   "PluginConfiguration": {
>     "Network": 5195086,
>     "Nodes": [ ],
>     "MaxTaskTimeout": 432000000,
>     "AllowPrivateHost": true,
>     "AllowedContentTypes": [ "application/json" ],
>     "Https": {
>       "Timeout": 15000
>     },
>     "NeoFS": {
>       "EndPoint": "127.0.0.1:8080",
>       "Timeout": 15000
>     },
>     "AutoStart": true
>   }
> }
> ```
> 
> Once the neo-node starts, this happens:
> 
> ![image](https://user-images.githubusercontent.com/2124276/111197169-6cc40c00-85be-11eb-8619-8fa0d350cb9f.png)
> 
> If I start by the neo-node CLI, it's fine -- it starts.
> 
> If I add `"http://localhost:40332"` or `"localhost:40332"` or whatever to the `Nodes` attribute, it doesn't start either. Same behavior.
> 
> Is there anything I'm doing wrong here? Please, give me some light. ⚡ 😄

Need vote for this address as 8 in the `Role` of `RoleManagementContract`, and need a little gas in this account for making initial transaction. The same to StateService.
![image](https://user-images.githubusercontent.com/38493437/111249094-1a2e3280-8646-11eb-9dbf-46c4dcb52b52.png)
![image](https://user-images.githubusercontent.com/38493437/111249135-2c0fd580-8646-11eb-87b6-9b289d4861ca.png)

For example, using RPC invokefunction:
```
{
  "jsonrpc": "2.0",
  "method": "invokefunction",
  "params": [
    "0x49cf4e5378ffcd4dec034fd98a174c5491e395e2",
    "designateAsRole",
    [
      {
        "type": "ByteArray",
        "value": "BA=="
      },
      {
        "type": "Array",
        "value": [
        {
        "type": "PublicKey",
        "value": "024bf3920eb18d162b46e9891defe24cd7b068818e5a268d352d2e28b1bc1dd7b7"
        }
        ]
      }
    ],
    [
      {
        "account": "NLq3LPLLCr77XLQ4UUwQpbg6CLTZ9sEieY",
        "scopes": "CalledByEntry"
      }
    ]
  ],
  "id": 3
}
```

**Comment by gsmachado** [comment]
@superboyiii oh, yes, I forgot that the oracle service just successfully starts with the votes already in place. I realized this after I posted here. All fine! Thanks! 😄
