### ISSUE TITLE
neo exit when oracle service set autostart as true and the active wallet is not the oracle node wallet

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-modules#526]
**Describe the bug**

1. do not set oracle nodes.
2. config.json in neo-cli, set the wallet as active but is not one of the oracle nodes.
2. set "autostart" in config.json of Oracle Service plugin.
3. Start neo node.

![794eb3fa6be13e9cd66572318045e21](https://user-images.githubusercontent.com/34291844/108667454-37bf1f00-7514-11eb-8c4c-e70a511b556a.png)

IF set oracle nodes as pre-condition, then the error message is:
![5c4dc10b1e50f0068207cda9f7732e2](https://user-images.githubusercontent.com/34291844/108672682-79a09300-751d-11eb-9653-b466ad8f03b3.png)

another scenario is dealt with correctly: 
when autostart of oracle is true, but the wallet is inactive. and open a non-oracle node wallet in the cli, it shows oracle service not available error.

![76413cb560c10e758ebcd0537e5c3e9](https://user-images.githubusercontent.com/34291844/108668259-d8620e80-7515-11eb-890c-75501e9271d7.png)

**Comment by shargon** [comment]
This wallet have the Oracle wallets?

**Comment by cloud8little** [comment]
> This wallet have the Oracle wallets?

nope.

**Comment by shargon** [comment]
Then maybe it's the expected behaviour, isn't it?

**Comment by cloud8little** [comment]
> Then maybe it's the expected behaviour, isn't it?

yes, but the neo client will exit after the error. I think it should show error and allow user to input further.
