### ISSUE TITLE
ApplicationLogs and StateService still use the magic to generate folder name

### ISSUE THREAD

**Issue by cloud8little** [neo-project/neo-modules#531]
![5d50749e6e829a4304384fabf0b20af](https://user-images.githubusercontent.com/34291844/109485316-7f1d5080-7abc-11eb-8810-6112f2f4a623.png)

![9731b7f721f057ecb5a592517dee703](https://user-images.githubusercontent.com/34291844/109485329-83e20480-7abc-11eb-939e-18ae56a199c8.png)

![16c70bfce352c07369a061fb11f37cc](https://user-images.githubusercontent.com/34291844/109485332-85abc800-7abc-11eb-902e-dfdaf6427df8.png)

**Comment by shargon** [comment]
I will fix it

**Comment by erikzhang** [comment]
Why shouldn't magic be used?

**Comment by cloud8little** [comment]
why some use magic, some does not?  @erikzhang 

![4bf774dbbff0505a80079e9c7878314](https://user-images.githubusercontent.com/34291844/109519214-fe734a00-7ae5-11eb-943b-f0df4bc5de6a.png)

**Comment by erikzhang** [comment]
I think all folders should contain the network magic number.

**Comment by cloud8little** [comment]
> I think all folders should contain the network magic number.

neo-cli will deal with Logs and Data_LevelDB folder without the magic number, should they also be updated? 

```cs
        public LoggerSettings(IConfigurationSection section)
        {
            this.Path = section.GetValue("Path", "Logs_{0}");
            this.ConsoleOutput = section.GetValue("ConsoleOutput", false);
            this.Active = section.GetValue("Active", false);
        }
```

```cs
        public StorageSettings(IConfigurationSection section)
        {
            this.Engine = section.GetValue("Engine", "LevelDBStore");
            this.Path = section.GetValue("Path", "Data_LevelDB_{0}");
        }
```
