### ISSUE TITLE
Magic and AddressVersion attributes in ProtocolConfiguration

### ISSUE THREAD

**Issue by gsmachado** [neo-project/neo-modules#548]
**Describe the bug**

It seems that `Magic` and `AddressVersion` can't co-exist in the  `ProtocolConfiguration`, somehow.

If this is intended, is there any missing config that was not set, somewhere?

**To Reproduce**

`config.json` with the following content, and leave all other Plugin files untouched:

```
{
  "ApplicationConfiguration": {
    "Logger": {
      "Path": "Logs",
      "ConsoleOutput": true,
      "Active": true
    },
    "Storage": {
      "Engine": "LevelDBStore",
      "Path": "Data_LevelDB_{0}"
    },
    "P2P": {
      "Port": 40333,
      "WsPort": 40334
    },
    "UnlockWallet": {
      "Path": "wallet.json",
      "Password": "neo",
      "IsActive": true
    },
    "PluginURL": "https://github.com/neo-project/neo-modules/releases/download/v{1}/{0}.zip"
  },
  "ProtocolConfiguration": {
    "Magic": 5195086,
    "AddressVersion": 53,
    "MillisecondsPerBlock": 15000,
    "MaxTraceableBlocks": 2102400,
    "ValidatorsCount": 1,
    "StandbyCommittee": [
        "036cfcc5d0550d0481b66f58e25067280f042b4933fc013dc4930ce2a4194c9d94"
    ],
    "SeedList": [
        "localhost:40333"
    ]
  }
}
```

BTW: `AddressVersion` with (decimal) value `53` is the default one.

Perform the following `curl` command:

```
curl http://127.0.0.1:10332 -d '{"jsonrpc":"2.0","method":"getblockcount","params":[],"id":1}'
```

The following error will come up:

```
{"jsonrpc":"2.0","id":1,"error":{"code":-2147467261,"message":"Object reference not set to an instance of an object."}}
```

**Comment by erikzhang** [comment]
@neo-project/ngd-shanghai Please check it.

**Comment by cloud8little** [comment]
@gsmachado The rpcserver method works well when I set the AddressVersion as 53. Can you check if the node works?

**Comment by gsmachado** [comment]
@cloud8little sorry. This issue was reproducible due to a config file problem. After I fixed, it's not reproducible anymore.

Closing it. Thanks for looking into it.
