### ISSUE TITLE
RpcServer Plugin: unexpected `invokecontractverify` behaviour

### ISSUE THREAD

**Issue by AnnaShaleva** [neo-project/neo-modules#552]
**Describe the bug**
Initially, `invokecontractverify` RPC API was created to define network fee for contract witness verification (https://github.com/neo-project/neo/issues/1977).  But it performs a `System.Contract.Call` instead of behaving like [Helper.VerifyWitness](https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Helper.cs#L190). So the resulting RPC verification fee got from `invokecontractverify` is different from the one we got during the real witness verification.

During real contract witness verification, the whole contract's script is loaded into VM, and then we jump to the verify method. Thus, to define the exact contract verification price, we should act like this (and not just perform the `System.Contract.Call` of the `verify` method).

**Expected behavior**
`invokecontractverify` behaviour should exactly match the  [`Helper.VerifyWitness` behaviour](https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/Helper.cs#L190) to calculate contract witness verification fee properly.

See https://github.com/nspcc-dev/neo-go/pull/1825 for the reference implementation.

**Platform:**
 - Version: Neo 3

**Comment by Ashuaidehao** [comment]
This api requires signers' private key in rpc node wallet, how to use it in client side? I wonder even after repair the behaviour, it cannot work properly in your scenarios.
