### ISSUE TITLE
neo-cli  dont created log folder

### ISSUE THREAD

**Issue by MaximSidorovRep** [neo-project/neo-modules#569]
Hi,
I run neo-cli version 2.12.2 with plugins 

        {
            "name": "ApplicationLogs",
            "version": "2.12.2.0",
            "interfaces": [
                "IRpcPlugin",
                "IPersistencePlugin"
            ]
        },
        {
            "name": "RpcWallet",
            "version": "2.12.2.0",
            "interfaces": [
                "IRpcPlugin"
            ]
        },
        {
            "name": "SimplePolicyPlugin",
            "version": "2.12.2.0",
            "interfaces": [
                "ILogPlugin",
                "IPolicyPlugin"
            ]
        }

As I understand it (SimplePolicyPlugin - "ILogPlugin" ) is responsible for logging, but log file not created.
From source code i saw creating folder log, but folder no created.
I run neo-cli with different parametrs:
```
dotnet neo-cli.dll --rpc --log
dotnet neo-cli.dll --rpc --logs
dotnet neo-cli.dll --rpc
```
What is the problem?

**Comment by Qiao-Jin** [comment]
Did any exception happen? Could you show the overall log?

**Comment by MaximSidorovRep** [comment]
After run 
`dotnet neo-cli.dll --rpc --log` me redirect to neo-cli

`root@66355b6e234b:/neo-cli# dotnet neo-cli.dll --rpc --log
NEO-CLI Version: 2.12.2.0

neo>`

I don see creating ane logs file, after start i saw created:
|-- ApplicationLogs_00746E41
|   |-- 000014.log
|   |-- CURRENT
|   |-- LOCK
|   |-- LOG
|   |-- LOG.old
|   `-- MANIFEST-000012
|-- Chain_00746E41
|   |-- 000082.ldb
|   |-- 000083.ldb
|   |-- 000084.ldb
|   |-- 000085.ldb
|   |-- 000086.ldb
|   |-- 000087.ldb
|   |-- 000088.ldb
|   |-- 000089.ldb
|   |-- 000090.ldb
|   |-- 000091.ldb
|   |-- 000092.ldb
|   |-- 000094.ldb
|   |-- 000095.log
|   |-- CURRENT
|   |-- LOCK
|   |-- LOG
|   |-- LOG.old
|   `-- MANIFEST-000093

**Comment by Qiao-Jin** [comment]
Did you ever type` start consensus` command or set `StartConsensus` to `true` in config?

**Comment by MaximSidorovRep** [comment]
I don't started consensus, now i started and logs file created `2021-03-24.log`
