### ISSUE TITLE
invokefunction with open wallet has internal hardcoded GAS limit

### ISSUE THREAD

**Issue by snowypowers** [neo-project/neo-modules#573]
**Describe the bug**
I have been trying to automate a simple setup for my private chain docker. One of the newer features I wish to add to my docker image is to have the chain have candidates registered so I can start voting. 

I discovered that no matter what settings I set, I seem to be unable to get `invokefunction` RPC call to return me a serialized transaction.

**To Reproduce**
1. `docker pull snowypowers/neo-privatenet:v3.0.0-rc1` (assuming you are connected to docker.io) [source](https://github.com/snowypowers/neo-privatenet-docker/tree/v3-solonet/v3/solonet/rc1)
2. Run the docker image (`docker run --rm -d  -p 20332:20332/tcp -p 20333:20333/tcp -p 20334:20334/tcp snowypowers/neo-privatenet:v3.0.0-rc1`)
3. Open the wallet with curl: `curl -d '{"jsonrpc": "2.0","method": "openwallet", "params": ["wallet.json","wallet"],"id": 3}' -H 'Content-Type: application/json' http://localhost:20332`
4. Attempt to `invokefunction` to register a candidate: 
```
curl -d '
{
    "jsonrpc": "2.0",
    "method": "invokefunction",
    "params": [
        "ef4073a0f2b305a38ec4050e4d3d28bc40ea63f5",
        "registerCandidate",
        [{
            "type": "ByteArray",
            "value": "AgKKmYJu3AyX0Y4itpMjc9kI0yOqf5JlanfsJuiGFpnv"
        }],
        [
            {
                "account": "b611bfa60886125e0071b56deeaf6efb40bd2336",
                "scopes": "Global"
            }
        ]
    ],
    "id": 3
}' -H 'Content-Type: application/json' http://localhost:20332
```
5. See that the response is:
```
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "script": "DCECAoqZgm7cDJfRjiK2kyNz2QjTI6p/kmVqd+wm6IYWme8RwB8MEXJlZ2lzdGVyQ2FuZGlkYXRlDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA70FifVtS",
        "state": "HALT",
        "gasconsumed": "100001045290",
        "exception": "Insufficient GAS.",
        "stack": [
            {
                "type": "Boolean",
                "value": true
            }
        ]
    }
}
```

Some digging through the code:

The RPC server calls (wallet.MakeTransaction)[https://github.com/neo-project/neo-modules/blob/v3.0.0-rc1/src/RpcServer/RpcServer.Wallet.cs#L181].
This leads me to [this line](https://github.com/neo-project/neo/blob/master/src/neo/Wallets/Wallet.cs#L394) which calls into [this](https://github.com/neo-project/neo/blob/v3.0.0-rc1/src/neo/Wallets/Wallet.cs#L470). At this point, I realise that there is a 20 GAS limit which is default and my RPC server failed to pass any of its settings in.

**Expected behavior**
I would expect that there is no exception as I have 10k GAS in each account. I expect that the field `tx` be present and I can actuate that through `sendrawtransaction`.

I would expect the RPC server to pass in either MaxFees or MaxInvokeGas which allows me to construct transactions that follows my expected limits stated in the config.

**Platform:**
 - OS: Windows using WSL2
 - Version: v3.0.0-rc1

**Comment by superboyiii** [comment]
@snowypowers Is https://github.com/neo-project/neo-modules/pull/574 enough for you? You could adjust `MaxInvokeGas` in config.json.
