### ISSUE TITLE
Add the root state of storage (leveldb) to the consensus

### ISSUE THREAD

**Issue by Liaojinghui** [neo-project/neo-modules#623]
**Summary or problem description**
We know that all nodes have the same block that contains exactly the same transactions after the consensus. However, we can not ensure that CNs have the same transaction execution results as neither did we put the transaction results into the consensus nor the block. Due to storage damage or other potential reasons, different nodes may have different execution results given the same transactions.

**Do you have any solution you want to propose?**
Add the `root state of the storage` of the primary to the `preparerequest` message, and other CNs check that value with their own storage root state, call for a `change view` if values do not match.

It would be even better if we could also write the storage root state into Block to make sure that all nodes not only have the same Chain Blocks, but also the same states.

**Where in the software does this update applies to?**
- Consensus
- Plugins

**Comment by roman-khimov** [comment]
neo-project/neo#1526

**Comment by Liaojinghui** [comment]
> neo-project/neo#1526

Its not in the header or consensus, did you have any conclusion on that in your last discussion?

**Comment by roman-khimov** [comment]
Well, it's all there for careful reader to go through and the net result probably can be seen in the protocol. At the same time it can be seen in `StateRootInHeader` protocol extension in NeoGo (that allows us also to make an extension for neo-project/neo#2373 which is a work in progress at the moment).

**Comment by Liaojinghui** [comment]
@roman-khimov  Appreciate your time answering questions from an uncareful reader then.

**Comment by roman-khimov** [comment]
@Liaojinghui, don't get me wrong, I'm all for making state root hash a part of the header (with block N containing state root for block N-1) in some Neo 3.1 and we have an extension in NeoGo for a reason, but there are also reasons why we don't have it in Neo 3.0 already.

**Comment by Liaojinghui** [comment]
> @Liaojinghui, don't get me wrong, I'm all for making state root hash a part of the header (with block N containing state root for block N-1) in some Neo 3.1 and we have an extension in NeoGo for a reason, but there are also reasons why we don't have it in Neo 3.0 already.

товарищи, i misunderstood you for one tiny second, but I realized i was wrong instantly. Please forgive my last foolish comment. I will punish myself to open more issues to keep bothering you, erik, and shargon. And thank you very much for your kindness.
