### ISSUE TITLE
Provide protocol configuration data via RPC

### ISSUE THREAD

**Issue by roman-khimov** [neo-project/neo-modules#636]
**Summary or problem description**
Clients may need some addition protocol configuration data to adjust their behaviour wrt the network. A typical thing is `MillisecondsPerBlock` value that could be used to adjust some timeouts/polling intervals. But `MaxValidUntilBlockIncrement` can also be useful to construct proper transactions as well as `MaxTraceableBlocks` to set some assumptions on data availability.

**Do you have any solution you want to propose?**
We can either create an additional API for that or just stuff this data into `getversion` (like it was done for #358).

**Where in the software does this update applies to?**
- RPC (HTTP)

**Comment by devhawk** [comment]
Also need to include Address Version in the list of RPC available protocol config
