### ISSUE TITLE
Shamir Secret service for Random Numbers

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#672]
Maybe we could have an extra service with an additional `Role` that will provide Shamir Secrets encrypted by validators' public keys.

Then, consensus nodes will publish that pieces of secrets during consensus, in which any `2f + 1` combination of Secrets will provide the current nonce.

Every round the Shamir Secrets Service will spread the `Secrets Pieces` on P2P, pointing that to the `PrevHash`.
Meanwhile, if our Shamir Secret Service is delayed we could normally use the strategy that is currently used with Primary only nonce. 

* The advantage is that we would have a separate entity for random and another one for transactions list.

* Smart contracts could optionally implement a verification that ensure Shamir Secrets random of the current block. Thus, if that was not obtained for that block then the tx will return false, something like that.

@igormcoelho @Qiao-Jin @Liaojinghui @shargon @erikzhang

**Comment by igormcoelho** [comment]
I think this is a very simple option, the issue is that the central agent that generates random numbers may be down (forcing a legacy random number being necessary)... but as long as contracts use this random together with  transaction/block hash information, it is hard to predict it, even random source is compromised, since the primary would also need to collude with this entity.

**Comment by shargon** [comment]
But how do you prevent that CN use his secret for his own benefit?

**Comment by vncoelho** [comment]
They do not have this power, @shargon.
Check https://iancoleman.io/shamir/

Their piece of secret does not reveal the nonce, which is only revealed when any `2f +1` consensus agrees with the TX List, which is our commit phase.

**Comment by shargon** [comment]
Who create the nonce?

**Comment by vncoelho** [comment]
The service,ajjajajaja

Elected by the committee.

Even if it is a single node, I do not see a problem because it will not pick the txs.

Nonces encrypted will be broadcasted beforehand.

**Comment by shargon** [comment]
> Even if it is a single node, I do not see a problem because it will not pick the txs.

who create the nonce could take the advantage of this information

**Comment by vncoelho** [comment]
That is true

**Comment by Liaojinghui** [comment]
I would say this is even more complex than BLS to implement and use.
