### ISSUE TITLE
Default MaxBlockSystemFee is not enough for registerring a candidate

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-modules#702]
**Describe the bug**
Transaction for registerring a candidate can't be persisted in block because default MaxBlockSystemFee in DBFTPlugin is not enough.

**To Reproduce**
Run a single CN and register another address for candidate

**Expected behavior**
Tx will not be processed by consensus but always in mempool as `verified` state. A issue from https://github.com/neo-project/neo-modules/pull/688, maybe can increase it to 300000000000.

**Comment by shargon** [comment]
Closed by #703
