### ISSUE TITLE
There is an error on Windows OS with regional settings in Turkish.

### ISSUE THREAD

**Issue by yildizoglu** [neo-project/neo-modules#711]
https://user-images.githubusercontent.com/17987913/166709904-43edeb04-63a0-4f7a-9b80-e24059161a9c.mp4

If  `toLower()` function used in the following line is replaced with `toLowerInvariant()`, the error can be fixed.
https://github.com/neo-project/neo-modules/blob/81eb9b78393a080075f53afbe7ae7d915693e712/src/RpcClient/RpcClient.cs#L159

**Comment by devhawk** [comment]
#712 fixed this, right?
