### ISSUE TITLE
RpcServer should support missing params request property

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-modules#768]
Some RPC methods (such as getbestblockhash) don't have any parameters. However, if the caller doesn't include an empty array in the request, `ProcessRequestAsync` returns an `Invalid Request` error message.

I recommend updating `ProcessRequestAsync` to validate the `params` property is an array if present and pass an empty array into the RPC method if not present

From [JSON-RPC 2.0 specification](https://www.jsonrpc.org/specification#request_object):

> **params**: A Structured value that holds the parameter values to be used during the invocation of the method. This member MAY be omitted.

**Comment by roman-khimov** [comment]
Duplicates #742.

**Comment by devhawk** [comment]
thanks for the heads up that this is a dupe. I think #769 is a cleaner fix than #747, but I'll let @shargon make the call
