### ISSUE TITLE
[Question] LevelDB store saving...

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-modules#804]
Why with level db then u delete and put data in the database. The database file keeps growing bigger and bigger. Event tho you are deleting the records so u can update it and put it back in. 

### example

```CSharp
var store = NeoSystem.LoadStore("Test");
var key = new KeyBuilder(999, 99).ToArray();
Span<byte> buffer = stackalloc byte[1024];

buffer.Fill(66);

while(true)
{
    if (store.Contains(key))
        store.Delete(key);
    store.Put(key, buffer.ToArray());
}
```

#### how would u update a record in the data store?

**Comment by shargon** [comment]
I suppose that like other types of databases, leveldb has to have some method to invoke compaction.

**Comment by cschuchardt88** [comment]
Thanks for the time and answer.
