### ISSUE TITLE
Remove unnecessary dll when build or publish a plugin

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-modules#848]
**Summary or problem description**
Our plugins have a complex dependency structure, for example, StateService need MPT, need RpcServer, need Neo, and Neo need Neo-VM, so when you build or publish a plugin, you may get many dll from these dependency, but what we what is just these necessary when taken them into `Plugins` path of neo-cli.

**Do you have any solution you want to propose?**
Plugins excluding `RpcServer` itself, don't need build `RpcServer` in publish,  `Neo` and `Neo.ConsoleService` as welll.
**Where in the software does this update applies to?**
- Plugins

**Comment by cschuchardt88** [comment]
you can add something like this

```xml
<PackageReference Include="coverlet.collector" Version="6.0.0">
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    <PrivateAssets>all</PrivateAssets>
</PackageReference>
```
