### ISSUE TITLE
Inclusion of new plugins

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#85]
Currently, there are good plugins, quite useful to the community, developed by communities and/or autonomous developers.

@hal0x2328, for example, recently did a good effort in two different plugins: 1- for monitoring CN; and 2- for local debugging.

Others type of plugins for testing are also useful during experimentation and etc.

While I also believe that we should keep this repository concise, I think that it should have more plugins.
Probably, in the future, it will not pass a number of 15-20 plugins.
When we reach such limit we would have already probably covered plenty of classes and applications. In this sense, if that time comes we might also just update plugins and keep improving them.

Otherwise, I am afraid that the community might need to create another repository for "extra" plugins. Without merging all that new good ideas we lose the ability of spreading good features that are being developed.

**Comment by hal0x2328** [comment]
I also have two more plugins I wrote:
https://github.com/hal0x2328/RpcFindStorage
https://github.com/hal0x2328/NeoPubSub

I agree that there should be some central resource for locating the source code of all plugins of interest to developers, I'm not sure all (or even any) of mine should be part of the official neo-plugins repository. 

I'm happy to write these plugins and share them freely but I won't always have the resources to maintain them long-term. So it kind of places a burden on NGD to have someone who can take over the code maintenance to make sure there is always a working build for every new Neo release, accept new PRs, check for security holes, etc for features that aren't mission-critical.

**Comment by lock9** [comment]
@neo-project/core  should we plan to add these new plugins? I think plugins are a good feature of NEO, maybe we should treat this "more nicely" 🤔

**Comment by igormcoelho** [comment]
I think that, as long as basic rules are followed, and plugin usage is justified, it should be welcome here. Breaking changes shouldn't be so common that all plugins are broken all the time... and if they are to be broken, better broken here (where we will know something is broken), than having people to fix them everywhere else, without full awareness of recent changes.
