### ISSUE TITLE
[3.6.2] GetNativeContracts Exception

### ISSUE THREAD

**Issue by Devel484** [neo-project/neo-modules#850]
**Describe the bug**
Calling the RPC Method GetNativeContracts results in an exception on client side. RPC side is sending a json object without the field `updatehistory`, but Client side is expecting the field.

https://github.com/neo-project/neo-modules/blob/64a1ae4c27b2a8d1285976231142b39bde49cc02/src/RpcClient/Models/RpcNativeContract.cs#L26-L36

https://github.com/neo-project/neo-modules/blob/64a1ae4c27b2a8d1285976231142b39bde49cc02/src/RpcServer/Utility.cs#L35-L44

**Comment by shargon** [comment]
I will remove it also in client according to https://github.com/neo-project/neo-modules/pull/828
