### ISSUE TITLE
DBFT plugin can't be loaded correctly

### ISSUE THREAD

**Issue by superboyiii** [neo-project/neo-modules#874]
**Describe the bug**
DBFT plugin will throw expection when running because it can't find `Store` due to the latest change of https://github.com/neo-project/neo/pull/3141

**To Reproduce**
1. Set up a single consensus node
2. Run node and start consensus

**Expected behavior**
Should run smoothly without any exception

**Screenshots**
![1708412317997](https://github.com/neo-project/neo-modules/assets/38493437/b87edd1f-209a-4c31-8895-4d1e79bb1c8a)
![image](https://github.com/neo-project/neo-modules/assets/38493437/e4c5ce8e-2b0a-4455-8c44-8a85e8926b2f)

**Platform:**
 - OS: Windows 10 x64
 - Version: Latest master branch

**`Pay Attention: Neo structure has been changed a lot, almost breaks every plugin. We need fix all of these.`**

**Comment by shargon** [comment]
It seems that you have "Store" in your config
