### ISSUE TITLE
Next version

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#883]
It looks like everything is working now,  devpack still needs to be updated.

Maybe it is time to release a version and then merge next major changes.
There were lots of changes that would be good to released.

**Comment by roman-khimov** [comment]
Obligatory link: https://github.com/neo-project/neo/issues/2905

**Comment by vncoelho** [comment]
> Obligatory link: https://github.com/neo-project/neo/issues/2905

Thanks
