### ISSUE TITLE
dotnet output folder not working for AppLog

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#890]
After commit https://github.com/neo-project/neo-modules/commit/42740769bb18004dccb1602ad57a836e3f3d43d3 the command `dotnet publish .... -o YOUR_FOLDER` is not publishing there but in `bin`
Perhaps it is related to some change in 

```cs
    <RootNamespace>Neo.Plugins</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
   <ProjectReference Include="..\..\neo\src\Neo.ConsoleService\Neo.ConsoleService.csproj" />
    <ProjectReference Include="..\RpcServer\RpcServer.csproj" AdditionalProperties="IncludeSettingsFileOutput=False">
    ```

ping @cschuchardt88

**Comment by shargon** [comment]
could you put the full command and the error?

**Comment by cschuchardt88** [comment]
@vncoelho 

_**Try running the following commands**_:
```bash
dotnet restore
dotnet publish ./src/ApplicationLogs --framework net7.0 --no-restore --configuration Release --output /app/Plugins/ApplicationLogs
```

**Comment by vncoelho** [comment]
> @vncoelho 
> 
> _**Try running the following commands**_:
> ```bash
> dotnet restore
> dotnet publish ./src/ApplicationLogs --framework net7.0 --no-restore --configuration Release --output /app/Plugins/ApplicationLogs
> ```

Command is exactly this.
Soon I will send more info
