### ISSUE TITLE
modified file when clonning repo

### ISSUE THREAD

**Issue by vncoelho** [neo-project/neo-modules#891]
![image](https://github.com/neo-project/neo-modules/assets/17395762/cb332e01-d819-4350-8050-2f91c9baaac6)

**Comment by vncoelho** [comment]
![image](https://github.com/neo-project/neo-modules/assets/17395762/8fbc6f9a-9582-4fe1-9fc4-d8a0205d1e7e)

**Comment by vncoelho** [comment]
```bash
warning: CRLF will be replaced by LF in src/ApplicationLogs/config.json.
The file will have its original line endings in your working directory
```

**Comment by shargon** [comment]
This file is with CRLF?

**Comment by cschuchardt88** [comment]
@vncoelho 

_**Run the following the commands**_:
```bash
git config --global core.autocrlf false # You must disable able this.

git add --renormalize .  # Update index with renormalized files
git status               # Show the files that will be normalized
git commit -m "Introduce end-of-line normalization"
```

**Comment by vncoelho** [comment]
I did something similar in the PR. I will double check on Monday

**Comment by vncoelho** [comment]
> This file is with CRLF?

Not sure Shargon.

If you clone the repo and type 'git status ' you will see something different.

This was introduced in last PR.
Since everything I run is dockerized I am sure there is something to be fixed.

**Comment by cschuchardt88** [comment]
@vncoelho By default `git` automatically changes the line endings to your computer's operating systems' line ending.

_**Default Line Endings per OS**_:
- `Windows=CRLF`
- `Unix=LF`
- `Linux=LF`
- `MacOS=LF`
